/*
 * PZ Online Decoration Tool
 * Copyright (C) 2026 PZ Online Decoration Tool contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
namespace PZODT {
  const APP_VERSION='1.0.0';
  type ReleaseConfig={feedbackEndpoint?:string;feedbackUrl?:string;supportUrl?:string};
  type TutorialStep={title:string;text:string;target?:string;openLoad?:boolean;closeLoad?:boolean};
  const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
  const storeGet=(k:string):string|null=>{try{return localStorage.getItem(k);}catch{return null;}};
  const storeSet=(k:string,v:string):void=>{try{localStorage.setItem(k,v);}catch{}};
  const storeRemove=(k:string):void=>{try{localStorage.removeItem(k);}catch{}};
  const releaseConfig=():ReleaseConfig=>{const x=(window as any).PZODT_RELEASE_CONFIG;return x&&typeof x==='object'?x:{};};
  const safeHttpsUrl=(value:unknown):string=>{if(typeof value!=='string'||!value.trim())return '';try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}};
  const safeSameOriginEndpoint=(value:unknown):string=>typeof value==='string'&&/^\/(?!\/)[A-Za-z0-9_./?=&%-]*$/.test(value)&&!value.includes('..')?value:'';
  const save=(name:string,blob:Blob)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  export class App{
    map=new PZMapModel(64,64);assets=new AssetManager();tileDefs=new TileDefDatabase();catalog=new CatalogManager(this.assets);importer=new PZWorldImportManager();history=new History();camera:Camera={panX:0,panY:0,zoom:.72};filters=new Map<ViewCategory,boolean>(VIEW_CATEGORIES.map(c=>[c,true]));classificationCache=new Map<string,ViewCategory>();
    renderer:WebGLMapRenderer;editor:EditorController;mediaReadySignature='';selectedFurnitureHit:FurnitureHit|null=null;tileToken=0;furnitureToken=0;furnitureObserver:IntersectionObserver|null=null;
    tutorialIndex=0;tutorialActive=false;tutorialSteps:TutorialStep[]=[
      {title:'Welcome',text:'This short guide walks through the normal workflow: load a Project Zomboid location, browse assets, decorate the map, and save the project.'},
      {title:'Load a PZ location',text:'Start here. Continue and the location loader will open so you can see the full import workflow.',target:'loadLocationBtn',closeLoad:true},
      {title:'The location loader',text:'Everything needed for importing a base is in this window: media folder, map dataset, world coordinates, and load mode.',target:'loadDialog',openLoad:true},
      {title:'Choose the media folder',text:'Choose the ProjectZomboid\\media folder. Map data, texture packs, PNG tilesheets, and tile definitions are indexed locally in the browser.',target:'chooseMediaBtn',openLoad:true},
      {title:'Enter world coordinates',text:'Enter the World X and World Y coordinates for the building or area you want to load.',target:'worldX',openLoad:true},
      {title:'Load the building',text:'For the usual base-planning workflow, keep Building at coordinate selected and press Load Location.',target:'loadBtn',openLoad:true},
      {title:'Control what you see',text:'View Filters hide walls, roofs, furniture, and other categories without rewriting the imported object stacks.',target:'viewFilters',closeLoad:true},
      {title:'Browse furniture',text:'The Furniture tab contains categorized, searchable multi-tile objects with thumbnails. Select one, then place it on the map.',target:'furnitureTabButton'},
      {title:'Edit the plan',text:'Use Pencil, Erase, Rectangle, Picker, and Pan. Layers and Z levels are available in the inspector on the right.',target:'toolrow'},
      {title:'Save the project',text:'Use Save as .json to keep the plan and Open .json file to continue later. Feedback is available from the top bar.',target:'saveJsonBtn'}
    ];
    status=el<HTMLSpanElement>('status');coords=el<HTMLSpanElement>('coords');tileList=el<HTMLDivElement>('tileList');furnitureList=el<HTMLDivElement>('furnitureList');tileSearch=el<HTMLInputElement>('tileSearch');furnitureSearch=el<HTMLInputElement>('furnitureSearch');tilesetSelect=el<HTMLSelectElement>('tilesetSelect');furnitureCategory=el<HTMLSelectElement>('furnitureCategory');availableOnly=el<HTMLInputElement>('availableOnly');assetSummary=el<HTMLDivElement>('assetSummary');preview=el<HTMLCanvasElement>('previewCanvas');selectionInfo=el<HTMLDivElement>('selectionInfo');orientationButtons=el<HTMLDivElement>('orientationButtons');selectionLabel=el<HTMLSpanElement>('selectionLabel');layersList=el<HTMLDivElement>('layersList');zLevel=el<HTMLSelectElement>('zLevel');stageBadge=el<HTMLDivElement>('stageBadge');graphicsQuality=el<HTMLSelectElement>('graphicsQuality');performanceStatsToggle=el<HTMLInputElement>('performanceStatsToggle');performanceStatsBox=el<HTMLDivElement>('performanceStats');nightModeToggle=el<HTMLInputElement>('nightModeToggle');
    constructor(){this.renderer=new WebGLMapRenderer(el('glCanvas'),el('overlayCanvas'),this.assets,()=>this.map,this.camera,n=>this.classify(n),c=>this.filters.get(c)!==false);this.editor=new EditorController(this.renderer,()=>this.map,this.catalog,n=>this.classify(n),n=>this.objectVisible(n),this.history);this.editor.onStatus=s=>this.setStatus(s);this.editor.onChanged=()=>this.mapChanged();this.editor.onSelection=()=>this.selectionChanged();this.assets.onChanged=()=>this.assetsChanged();this.bind();this.renderFilterButtons();this.renderFurnitureCategories();this.refreshAll();const saved=storeGet('pzodt.graphicsQuality'),q:GraphicsQuality=saved==='low'||saved==='medium'||saved==='high'?saved:'high';this.graphicsQuality.value=q;this.renderer.setQuality(q);const perf=storeGet('pzodt.performanceStats')==='1';this.performanceStatsToggle.checked=perf;this.setPerformanceStats(perf);const night=storeGet('pzodt.nightMode')!=='0';this.nightModeToggle.checked=night;this.applyNightMode(night,false);setTimeout(()=>this.renderer.center(),50);this.configureRelease();setTimeout(()=>this.maybeStartTutorial(),250);}
    classify(n:string):ViewCategory{let c=this.classificationCache.get(n);if(c)return c;c=this.tileDefs.classify(n,this.catalog.furnitureTiles);this.classificationCache.set(n,c);return c;}
    objectVisible(n:string):boolean{return this.filters.get(this.classify(n))!==false;}
    setStatus(s:string){this.status.textContent=s;}
    bind(){document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>this.editor.setTool(b.dataset.tool as ToolName));document.querySelectorAll<HTMLButtonElement>('.tab').forEach(b=>b.onclick=()=>this.setTab(b.dataset.tab==='furniture'?'furniture':'tiles'));
      el<HTMLButtonElement>('rotateBtn').onclick=()=>this.editor.rotateFurniture(1);el<HTMLButtonElement>('undoBtn').onclick=()=>this.editor.undo();el<HTMLButtonElement>('redoBtn').onclick=()=>this.editor.redo();el<HTMLButtonElement>('centerBtn').onclick=()=>this.renderer.center();
      el<HTMLButtonElement>('newMapBtn').onclick=()=>this.newMap();el<HTMLButtonElement>('loadLocationBtn').onclick=()=>el<HTMLDialogElement>('loadDialog').showModal();el<HTMLButtonElement>('saveJsonBtn').onclick=()=>save('pz-online-decoration.json',new Blob([JSON.stringify({map:this.map.toJSON(),filters:Object.fromEntries(this.filters)})],{type:'application/json'}));el<HTMLButtonElement>('openJsonBtn').onclick=()=>el<HTMLInputElement>('jsonInput').click();
      el<HTMLButtonElement>('settingsBtn').onclick=()=>el<HTMLDialogElement>('settingsDialog').showModal();el<HTMLButtonElement>('settingsCloseBtn').onclick=el<HTMLButtonElement>('settingsDoneBtn').onclick=()=>el<HTMLDialogElement>('settingsDialog').close();this.graphicsQuality.onchange=()=>{const q=this.graphicsQuality.value as GraphicsQuality;storeSet('pzodt.graphicsQuality',q);this.renderer.setQuality(q);setTimeout(()=>this.renderer.center(),0);this.setStatus(`Graphics: ${q}.`);};this.performanceStatsToggle.onchange=()=>{storeSet('pzodt.performanceStats',this.performanceStatsToggle.checked?'1':'0');this.setPerformanceStats(this.performanceStatsToggle.checked);};
      el<HTMLButtonElement>('startTutorialBtn').onclick=()=>{el<HTMLDialogElement>('settingsDialog').close();this.startTutorial(true);};el<HTMLButtonElement>('creditsBtn').onclick=()=>{el<HTMLDialogElement>('settingsDialog').close();el<HTMLDialogElement>('creditsDialog').showModal();};el<HTMLButtonElement>('creditsCloseBtn').onclick=el<HTMLButtonElement>('creditsDoneBtn').onclick=()=>el<HTMLDialogElement>('creditsDialog').close();el<HTMLButtonElement>('feedbackBtn').onclick=()=>this.openFeedback();this.nightModeToggle.onchange=()=>this.applyNightMode(this.nightModeToggle.checked,true);el<HTMLButtonElement>('feedbackCloseBtn').onclick=()=>el<HTMLDialogElement>('feedbackDialog').close();el<HTMLButtonElement>('feedbackCopyBtn').onclick=()=>this.copyFeedback();el<HTMLButtonElement>('feedbackSendBtn').onclick=()=>this.sendFeedback();el<HTMLButtonElement>('supportBtn').onclick=()=>this.openSupport();
      el<HTMLButtonElement>('tutorialSkipBtn').onclick=()=>this.finishTutorial();el<HTMLButtonElement>('tutorialBackBtn').onclick=()=>this.moveTutorial(-1);el<HTMLButtonElement>('tutorialNextBtn').onclick=()=>this.moveTutorial(1);addEventListener('resize',()=>this.positionTutorial());
      document.querySelectorAll<HTMLFormElement>('dialog form').forEach(f=>f.addEventListener('submit',e=>e.preventDefault()));
      el<HTMLButtonElement>('collapseLeftBtn').onclick=()=>this.collapse('left',true);el<HTMLButtonElement>('openLeftPanelBtn').onclick=()=>this.collapse('left',false);el<HTMLButtonElement>('collapseRightBtn').onclick=()=>this.collapse('right',true);el<HTMLButtonElement>('openRightPanelBtn').onclick=()=>this.collapse('right',false);
      this.tileSearch.oninput=()=>this.renderTiles();this.tilesetSelect.onchange=()=>this.renderTiles();this.furnitureSearch.oninput=()=>this.renderFurniture();this.furnitureCategory.onchange=()=>this.renderFurniture();this.availableOnly.onchange=()=>this.renderFurniture();
      this.zLevel.onchange=()=>{this.map.currentLevel=+this.zLevel.value;this.stageBadge.textContent=`Z ${this.map.currentLevel} · perspective`;this.renderLayers();this.renderer.request();};el<HTMLButtonElement>('addLevelBtn').onclick=()=>{this.map.currentLevel=this.map.maxLevel()+1;this.renderLevels();this.renderer.request();};el<HTMLButtonElement>('addLayerBtn').onclick=()=>{const n=(prompt('Layer name','Decoration')||'').trim().slice(0,128);if(!n)return;this.map.addLayer(n,this.map.currentLevel,'Custom');this.renderLayers();};
      el<HTMLButtonElement>('chooseMediaBtn').onclick=()=>el<HTMLInputElement>('mediaInput').click();el<HTMLButtonElement>('loadCancelBtn').onclick=()=>el<HTMLDialogElement>('loadDialog').close();el<HTMLSelectElement>('loadMode').onchange=()=>this.updateLoadMode();el<HTMLButtonElement>('loadBtn').onclick=()=>this.loadLocation();el<HTMLButtonElement>('indexMediaBtn').onclick=()=>this.indexMediaOnly();
      el<HTMLInputElement>('mediaInput').onchange=e=>this.mediaSelected(e);el<HTMLInputElement>('jsonInput').onchange=e=>this.jsonSelected(e);
      this.renderer.overlay.addEventListener('pointermove',e=>{const r=this.renderer.overlay.getBoundingClientRect(),p=this.renderer.screenToTile(e.clientX-r.left,e.clientY-r.top,this.map.currentLevel),ox=Number(this.map.properties['pzodt.worldOriginX']),oy=Number(this.map.properties['pzodt.worldOriginY']);this.coords.textContent=Number.isFinite(ox)&&Number.isFinite(oy)?`local ${p.x},${p.y} · world ${ox+p.x},${oy+p.y},${this.map.currentLevel}`:`x ${p.x} · y ${p.y} · Z ${this.map.currentLevel}`;});
    }
    collapse(side:'left'|'right',yes:boolean){const l=document.querySelector<HTMLElement>('.layout')!;l.classList.toggle(`${side}-collapsed`,yes);el<HTMLButtonElement>(side==='left'?'openLeftPanelBtn':'openRightPanelBtn').classList.toggle('hidden',!yes);setTimeout(()=>{this.renderer.resize();this.renderer.request();},0);}
    setTab(t:'tiles'|'furniture'){document.querySelectorAll<HTMLElement>('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));el('tilesTab').classList.toggle('active',t==='tiles');el('furnitureTab').classList.toggle('active',t==='furniture');t==='tiles'?this.renderTiles():this.renderFurniture();}
    newMap(){if((this.map.layers.some(l=>l.cells.size)||[...this.map.baseStacks.values()].some(m=>m.size))&&!confirm('Start a new map? Unsaved edits will be lost.'))return;this.map=new PZMapModel(64,64);this.history=new History();(this.editor as any).history=this.history;this.renderer.mapReplaced();this.refreshAll();this.renderer.center();}
    async mediaSelected(e:Event){const inp=e.target as HTMLInputElement;if(!inp.files?.length)return;if(inp.files.length>100000){this.setStatus('Media folder contains too many files to index safely.');inp.value='';return;}const list=this.importer.scan(inp.files);const select=el<HTMLSelectElement>('datasetSelect');select.replaceChildren();for(const d of list){const o=document.createElement('option');o.value=d.id;o.textContent=`${d.label} · ${d.headers} headers / ${d.packs} lotpacks`;select.appendChild(o);}el<HTMLButtonElement>('loadBtn').disabled=!list.length;el<HTMLButtonElement>('indexMediaBtn').disabled=!list.length;el<HTMLDivElement>('mediaInfo').textContent=list.length?`${list.length} map dataset(s) found. ${this.importer.assetFiles().length} texture source file(s), ${this.importer.tileDefFiles().length} .tiles definition file(s).`:'No map dataset found in this media folder.';if(this.mediaReadySignature&&this.mediaReadySignature!==this.importer.mediaSignature){this.assets.clear();this.tileDefs.clear();this.classificationCache.clear();this.mediaReadySignature='';}inp.value='';}
    updateLoadMode(){const m=el<HTMLSelectElement>('loadMode').value;el('marginRow').classList.toggle('hidden',m!=='building');el('areaRow').classList.toggle('hidden',m!=='area');}
    async ensureMediaReady(progress:(s:string)=>void){if(this.mediaReadySignature===this.importer.mediaSignature&&this.mediaReadySignature){progress('Media library already indexed — reusing cached tiles, .pack textures and .tiles properties.');return;}progress('Indexing local media assets…');const a=await this.assets.loadMediaFiles(this.importer.assetFiles(),progress);const props=await this.tileDefs.loadFiles(this.importer.tileDefFiles(),progress);this.classificationCache.clear();this.renderer.invalidateAllGeometry();this.mediaReadySignature=this.importer.mediaSignature;progress(`Media ready: ${this.assets.assets.size.toLocaleString()} sprites · ${props.toLocaleString()} property-bearing tile definitions${a.skipped?` · ${a.skipped} cached files skipped`:''}.`);}
    async indexMediaOnly(){const st=el<HTMLDivElement>('loadStatus'),btn=el<HTMLButtonElement>('indexMediaBtn');if(!el<HTMLSelectElement>('datasetSelect').value){st.textContent='Select the Project Zomboid media folder first.';return;}btn.disabled=true;try{const progress=(s:string)=>{st.textContent=s;this.setStatus(s);};await this.ensureMediaReady(progress);this.renderTilesets();this.renderTiles();this.renderFurniture();this.selectionChanged();st.textContent='Media library ready. Current map was not changed.';}catch(err){st.textContent=`Media error: ${String((err as Error).message||err)}`;}finally{btn.disabled=false;}}
    async loadLocation(){const ds=el<HTMLSelectElement>('datasetSelect').value,x=+el<HTMLInputElement>('worldX').value,y=+el<HTMLInputElement>('worldY').value,mode=el<HTMLSelectElement>('loadMode').value as PZImportMode,margin=+el<HTMLInputElement>('marginInput').value,aw=+el<HTMLInputElement>('areaW').value,ah=+el<HTMLInputElement>('areaH').value,st=el<HTMLDivElement>('loadStatus'),btn=el<HTMLButtonElement>('loadBtn');if(!ds||!Number.isFinite(x)||!Number.isFinite(y)){st.textContent='Select media and enter valid World X / Y.';return;}btn.disabled=true;try{const progress=(s:string)=>{st.textContent=s;this.setStatus(s);};await this.ensureMediaReady(progress);const r=await this.importer.importLocation({datasetId:ds,x:Math.round(x),y:Math.round(y),mode,margin:Math.max(0,margin|0),areaWidth:Math.max(1,aw|0),areaHeight:Math.max(1,ah|0)},progress);this.map=r.map;this.history=new History();this.renderer.mapReplaced();(this.editor as any).history=this.history;this.refreshAll();this.renderer.center();const missing=[...r.usedTiles].filter(n=>!this.assets.asset(n));const msg=`Loaded ${r.buildingName||mode}: ${r.bounds.w}×${r.bounds.h}, ${r.importedSprites.toLocaleString()} sprites${missing.length?` · ${missing.length.toLocaleString()} texture(s) unresolved`:''}.`;this.setStatus(msg);st.textContent=msg;el<HTMLDialogElement>('loadDialog').close();}catch(err){const msg=`Load error: ${String((err as Error).message||err)}`;console.error(err);st.textContent=msg;this.setStatus(msg);}finally{btn.disabled=false;}}
    async jsonSelected(e:Event){const inp=e.target as HTMLInputElement,f=inp.files?.[0];if(!f)return;try{if(f.size>128*1024*1024)throw new Error('JSON project is larger than the 128 MiB safety limit.');const o=JSON.parse(await f.text()),m=o?.map??o;this.validateProjectData(m);this.map=PZMapModel.fromJSON(m);this.renderer.mapReplaced();if(o&&typeof o==='object'&&o.filters)for(const c of VIEW_CATEGORIES)this.filters.set(c,o.filters[c]!==false);this.history=new History();(this.editor as any).history=this.history;this.refreshAll();this.renderer.center();this.setStatus('JSON project opened. Load the same media folder if textures are not currently indexed.');}catch(err){this.setStatus(`JSON error: ${String((err as Error).message||err)}`);}inp.value='';}
    renderFilterButtons(){const box=el<HTMLDivElement>('viewFilters');box.replaceChildren();for(const c of VIEW_CATEGORIES){const b=document.createElement('button');b.className='viewFilter';b.textContent=c;b.onclick=()=>{const v=this.filters.get(c)!;this.filters.set(c,!v);b.classList.toggle('off',v);this.renderer.request();};box.appendChild(b);}}
    refreshAll(){this.renderLevels();this.renderLayers();this.renderTilesets();this.renderTiles();this.renderFurnitureCategories();this.renderFurniture();this.selectionChanged();this.renderFilterState();this.renderer.request();}
    mapChanged(){this.renderLevels();this.renderLayers();this.renderer.request();}
    assetsChanged(){this.classificationCache.clear();this.renderer.assetsChanged();this.renderTilesets();this.renderTiles();this.renderFurniture();this.selectionChanged();this.renderer.request();}
    renderFilterState(){const box=el('viewFilters');[...box.querySelectorAll<HTMLButtonElement>('.viewFilter')].forEach(b=>b.classList.toggle('off',this.filters.get(b.textContent as ViewCategory)===false));}
    renderLevels(){const ls=this.map.levels();if(!ls.includes(this.map.currentLevel))ls.push(this.map.currentLevel);ls.sort((a,b)=>a-b);this.zLevel.replaceChildren();for(const z of ls){const o=document.createElement('option');o.value=String(z);o.textContent=`Z ${z}`;this.zLevel.appendChild(o);}this.zLevel.value=String(this.map.currentLevel);this.stageBadge.textContent=`Z ${this.map.currentLevel} · perspective`;}
    renderLayers(){this.layersList.replaceChildren();const base=document.createElement('div');base.className='layer'+(this.map.activeTarget==='base'?' active':'');const eye=this.icon(this.map.baseVisible?'●':'○','Visibility',()=>{this.map.baseVisible=!this.map.baseVisible;this.renderLayers();this.renderer.request();});const lock=this.icon(this.map.baseLocked?'🔒':'🔓','Lock / unlock',()=>{this.map.baseLocked=!this.map.baseLocked;this.renderLayers();});const name=document.createElement('div');name.className='lname';name.textContent='Imported Base';name.onclick=()=>{this.map.activeTarget='base';this.renderLayers();};const op=document.createElement('input');op.type='range';op.min='0';op.max='1';op.step='.05';op.value=String(this.map.baseOpacity);op.oninput=()=>{this.map.baseOpacity=+op.value;this.renderer.request();};base.append(eye,lock,name,op,document.createElement('span'),document.createElement('span'),document.createElement('span'));this.layersList.appendChild(base);
      const arr=this.map.layers.map((l,i)=>({l,i})).filter(x=>x.l.level===this.map.currentLevel).sort((a,b)=>b.i-a.i);for(const {l} of arr){const row=document.createElement('div');row.className='layer'+(this.map.activeTarget===l.id?' active':'');const e=this.icon(l.visible?'●':'○','Visibility',()=>{l.visible=!l.visible;this.renderLayers();this.renderer.request();}),k=this.icon(l.locked?'🔒':'🔓','Lock / unlock',()=>{l.locked=!l.locked;this.renderLayers();}),n=document.createElement('div');n.className='lname';n.textContent=l.name;n.title=l.category;n.onclick=()=>{this.map.activeTarget=l.id;this.renderLayers();};const o=document.createElement('input');o.type='range';o.min='0';o.max='1';o.step='.05';o.value=String(l.opacity);o.oninput=()=>{l.opacity=+o.value;this.renderer.request();};const up=this.icon('↑','Move up',()=>{this.map.moveLayer(l.id,1);this.renderer.invalidateAllGeometry();this.renderLayers();this.renderer.request();}),dn=this.icon('↓','Move down',()=>{this.map.moveLayer(l.id,-1);this.renderer.invalidateAllGeometry();this.renderLayers();this.renderer.request();}),del=this.icon('×','Delete',()=>{if(confirm(`Delete ${l.name}?`)){this.map.deleteLayer(l.id);this.renderer.invalidateAllGeometry();this.renderLayers();this.renderer.request();}});row.append(e,k,n,o,up,dn,del);this.layersList.appendChild(row);}}
    icon(t:string,title:string,fn:()=>void){const b=document.createElement('button');b.className='iconbtn';b.textContent=t;b.title=title;b.onclick=fn;return b;}
    renderTilesets(){const old=this.tilesetSelect.value;this.tilesetSelect.replaceChildren();const all=document.createElement('option');all.value='';all.textContent='All tilesets';this.tilesetSelect.appendChild(all);for(const n of this.assets.tilesetNames()){const o=document.createElement('option');o.value=n;o.textContent=n;this.tilesetSelect.appendChild(o);}if([...this.tilesetSelect.options].some(o=>o.value===old))this.tilesetSelect.value=old;this.assetSummary.textContent=this.assets.assets.size?`${this.assets.assets.size.toLocaleString()} sprites · ${this.tileDefs.props.size.toLocaleString()} tile definitions`:'Load a PZ location to index the media library.';}
    renderTiles(){const token=++this.tileToken;this.tileList.replaceChildren();let a=this.tilesetSelect.value?this.assets.assetsForTileset(this.tilesetSelect.value):this.assets.search(this.tileSearch.value,500);if(this.tilesetSelect.value&&this.tileSearch.value.trim()){const q=this.tileSearch.value.toLowerCase();a=a.filter(x=>x.name.toLowerCase().includes(q));}const f=document.createDocumentFragment();for(const x of a.slice(0,500)){const d=document.createElement('div');d.className='tilecard'+(this.editor.selectedAsset===x.name?' selected':'');const c=document.createElement('canvas');c.width=90;c.height=82;const n=document.createElement('div');n.className='name';n.textContent=x.name;d.append(c,n);d.onclick=()=>{this.editor.selectAsset(x.name);this.renderTiles();};f.appendChild(d);this.assets.drawPreview(c,x.name).catch(()=>{});}if(token===this.tileToken)this.tileList.appendChild(f);}
    renderFurnitureCategories(){const old=this.furnitureCategory.value;this.furnitureCategory.replaceChildren();const all=document.createElement('option');all.value='';all.textContent='All furniture categories';this.furnitureCategory.appendChild(all);for(const c of this.catalog.categories()){const o=document.createElement('option');o.value=c;o.textContent=c;this.furnitureCategory.appendChild(o);}if([...this.furnitureCategory.options].some(o=>o.value===old))this.furnitureCategory.value=old;}
    renderFurniture(){const token=++this.furnitureToken;this.furnitureList.replaceChildren();const hits=this.catalog.search(this.furnitureSearch.value,this.furnitureCategory.value,300).filter(h=>!this.availableOnly.checked||h.available===h.total);if(!hits.length){const empty=document.createElement('div');empty.className='hint';empty.textContent='No matching available furniture.';this.furnitureList.appendChild(empty);return;}const f=document.createDocumentFragment(),previews:Array<{c:HTMLCanvasElement;h:FurnitureHit}>=[];for(const h of hits){const d=document.createElement('div');d.className='furnitureitem'+(this.selectedFurnitureHit?.groupIndex===h.groupIndex&&this.selectedFurnitureHit?.furnitureIndex===h.furnitureIndex?' selected':'');const c=document.createElement('canvas');c.className='furniturethumb';c.width=78;c.height=72;const t=document.createElement('div');t.className='furnituretext';const title=document.createElement('b');title.textContent=`${h.group.label} · #${h.def.index}`;const meta=document.createElement('small');meta.textContent=`${h.def.entries.length} orientations · ${h.available}/${h.total} tiles`;t.append(title,meta);d.append(c,t);d.onclick=()=>{this.selectedFurnitureHit=h;this.editor.selectFurniture(h.def);this.renderFurniture();};f.appendChild(d);previews.push({c,h});}this.furnitureList.appendChild(f);this.furnitureObserver?.disconnect();this.furnitureObserver=new IntersectionObserver(es=>{for(const e of es)if(e.isIntersecting){const q=previews.find(x=>x.c===e.target);if(q){this.furnitureObserver?.unobserve(q.c);this.drawFurniture(q.c,q.h.def,q.h.def.entries[0]?.orient||'N',()=>token===this.furnitureToken&&q.c.isConnected).catch(()=>{});}}},{root:this.furnitureList,rootMargin:'120px'});for(const q of previews)this.furnitureObserver.observe(q.c);}
    selectionChanged(){document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===this.editor.tool));this.renderSelection();}
    async renderSelection(){const ctx=this.preview.getContext('2d')!;ctx.clearRect(0,0,this.preview.width,this.preview.height);this.orientationButtons.replaceChildren();if(this.editor.selectedAsset){this.selectionLabel.textContent=this.editor.selectedAsset;const a=this.assets.asset(this.editor.selectedAsset),props=this.tileDefs.properties(this.editor.selectedAsset),cat=this.classify(this.editor.selectedAsset);this.selectionInfo.textContent=`${cat}\n${this.editor.selectedAsset}${Object.keys(props).length?`\nProperties: ${Object.keys(props).slice(0,8).join(', ')}`:''}`;if(a)await this.assets.drawPreview(this.preview,a.name);return;}const d=this.editor.selectedFurniture;if(d){const h=this.selectedFurnitureHit;this.selectionLabel.textContent=`${h?.group.label||'Furniture'} · ${this.editor.furnitureOrient}`;this.selectionInfo.textContent=`Furniture\n${h?.group.label||''} · #${d.index}\n${d.layer}`;for(const o of this.catalog.orientations(d)){const b=document.createElement('button');b.textContent=o;b.classList.toggle('active',o===this.editor.furnitureOrient);b.onclick=()=>{this.editor.furnitureOrient=o;this.selectionChanged();};this.orientationButtons.appendChild(b);}await this.drawFurniture(this.preview,d,this.editor.furnitureOrient);return;}this.selectionLabel.textContent='No tile selected';this.selectionInfo.textContent='Nothing selected.';}
    async drawFurniture(c:HTMLCanvasElement,d:FurnitureDef,o:string,guard:()=>boolean=()=>true){const e=this.catalog.entry(d,o);if(!e)return;const parts:Array<any>=[];for(const [dx,dy,n] of e.cells){const a=this.assets.asset(n);if(!a)continue;try{parts.push({a,b:await this.assets.bitmap(a.sourceId),dx,dy});}catch{}}if(!parts.length||!guard())return;const ds=this.assets.dominantScale(),tw=64*ds,th=32*ds;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const loc=parts.map(p=>{const bx=(p.dx-p.dy)*tw/2,by=(p.dx+p.dy)*th/2,s=ds/(p.a.scale||1),fw=p.a.frameW*s,fh=p.a.frameH*s,l=bx-fw/2+p.a.offsetX*s,t=by+th-fh+p.a.offsetY*s,r=l+p.a.sw*s,bb=t+p.a.sh*s;minX=Math.min(minX,l);minY=Math.min(minY,t);maxX=Math.max(maxX,r);maxY=Math.max(maxY,bb);return{...p,l,t,s};}).sort((a,b)=>(a.dx+a.dy)-(b.dx+b.dy)||a.dy-b.dy);const pad=4,w=Math.max(1,maxX-minX),h=Math.max(1,maxY-minY),fit=Math.min((c.width-pad*2)/w,(c.height-pad*2)/h,1),ox=(c.width-w*fit)/2-minX*fit,oy=(c.height-h*fit)/2-minY*fit,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;for(const p of loc){const a=p.a;ctx.drawImage(p.b,a.sx,a.sy,a.sw,a.sh,ox+p.l*fit,oy+p.t*fit,a.sw*p.s*fit,a.sh*p.s*fit);}}
    configureRelease(){const cfg=releaseConfig(),support=safeHttpsUrl(cfg.supportUrl);el<HTMLButtonElement>('supportBtn').classList.toggle('hidden',!support);}
    applyNightMode(enabled:boolean,persist=true){this.nightModeToggle.checked=enabled;document.body.classList.toggle('lightMode',!enabled);this.renderer.setNightMode(enabled);if(persist)storeSet('pzodt.nightMode',enabled?'1':'0');}
    maybeStartTutorial(){if(storeGet('pzodt.tutorialDismissed.1.0')!=='1')this.startTutorial(false);}
    startTutorial(force=false){if(this.tutorialActive)return;if(force)storeRemove('pzodt.tutorialDismissed.1.0');this.tutorialActive=true;this.tutorialIndex=0;el<HTMLInputElement>('tutorialRemember').checked=true;document.querySelectorAll<HTMLElement>('header,.toolrow,.layout,footer').forEach(x=>x.inert=true);const overlay=el<HTMLDivElement>('tutorialOverlay');overlay.inert=false;overlay.classList.remove('hidden');this.showTutorialStep();setTimeout(()=>el<HTMLButtonElement>('tutorialNextBtn').focus(),0);}
    moveTutorial(delta:number){if(!this.tutorialActive)return;const next=this.tutorialIndex+delta;if(next<0)return;if(next>=this.tutorialSteps.length){this.finishTutorial();return;}this.tutorialIndex=next;this.showTutorialStep();}
    finishTutorial(){if(!this.tutorialActive)return;this.tutorialActive=false;if(el<HTMLInputElement>('tutorialRemember').checked)storeSet('pzodt.tutorialDismissed.1.0','1');else storeRemove('pzodt.tutorialDismissed.1.0');const overlay=el<HTMLDivElement>('tutorialOverlay');overlay.classList.add('hidden');overlay.classList.remove('noTarget','cardTop');document.querySelectorAll<HTMLElement>('header,.toolrow,.layout,footer').forEach(x=>x.inert=false);const d=el<HTMLDialogElement>('loadDialog');d.classList.remove('tutorialVisibleDialog');if(d.open)d.close();el<HTMLDivElement>('tutorialSpotlight').classList.remove('active');}
    showTutorialStep(){const step=this.tutorialSteps[this.tutorialIndex],load=el<HTMLDialogElement>('loadDialog');if(step.closeLoad&&load.open){load.classList.remove('tutorialVisibleDialog');load.close();}if(step.openLoad){load.classList.add('tutorialVisibleDialog');if(!load.open)load.show();}if(step.target==='viewFilters')this.collapse('right',false);if(step.target==='furnitureTabButton')this.collapse('left',false);el<HTMLHeadingElement>('tutorialTitle').textContent=step.title;el<HTMLParagraphElement>('tutorialText').textContent=step.text;el<HTMLDivElement>('tutorialProgress').textContent=`${this.tutorialIndex+1} / ${this.tutorialSteps.length}`;el<HTMLButtonElement>('tutorialBackBtn').disabled=this.tutorialIndex===0;el<HTMLButtonElement>('tutorialNextBtn').textContent=this.tutorialIndex===this.tutorialSteps.length-1?'Finish':'Continue';requestAnimationFrame(()=>this.positionTutorial());}
    positionTutorial(){if(!this.tutorialActive)return;const step=this.tutorialSteps[this.tutorialIndex],spot=el<HTMLDivElement>('tutorialSpotlight'),overlay=el<HTMLDivElement>('tutorialOverlay');overlay.classList.toggle('noTarget',!step.target);overlay.classList.remove('cardTop');if(!step.target){spot.classList.remove('active');return;}const target=document.getElementById(step.target);if(!target||target.getClientRects().length===0){spot.classList.remove('active');overlay.classList.add('noTarget');return;}const r=target.getBoundingClientRect(),pad=10;spot.classList.add('active');spot.style.left=`${Math.max(4,r.left-pad)}px`;spot.style.top=`${Math.max(4,r.top-pad)}px`;spot.style.width=`${Math.max(24,Math.min(innerWidth-8,r.width+pad*2))}px`;spot.style.height=`${Math.max(24,Math.min(innerHeight-8,r.height+pad*2))}px`;overlay.classList.toggle('cardTop',r.top+r.height/2>innerHeight*.58);}
    configureFeedbackText():string{const type=el<HTMLSelectElement>('feedbackType').value,msg=el<HTMLTextAreaElement>('feedbackMessage').value.trim().slice(0,6000),contact=el<HTMLInputElement>('feedbackContact').value.trim().slice(0,200),technical=el<HTMLInputElement>('feedbackTechnical').checked;const lines=[`PZ Online Decoration Tool ${APP_VERSION}`,`Type: ${type}`,'',msg];if(contact)lines.push('',`Contact: ${contact}`);if(technical)lines.push('','Technical information:',`Browser: ${navigator.userAgent.slice(0,500)}`,`Graphics: ${this.graphicsQuality.value}`);return lines.join('\n');}
    openFeedback(){el<HTMLDivElement>('feedbackStatus').textContent='Your feedback stays in this browser until you submit or copy it.';el<HTMLDialogElement>('feedbackDialog').showModal();}
    async copyText(text:string):Promise<void>{if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(text);return;}const ta=document.createElement('textarea');ta.value=text;ta.readOnly=true;ta.className='clipboardFallback';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(!ok)throw new Error('Clipboard copy was blocked by the browser.');}
    async copyFeedback(){const st=el<HTMLDivElement>('feedbackStatus'),text=this.configureFeedbackText();if(!el<HTMLTextAreaElement>('feedbackMessage').value.trim()){st.textContent='Write a message first.';return;}try{await this.copyText(text);st.textContent='Feedback copied to the clipboard.';}catch(err){st.textContent=String((err as Error).message||err);}}
    openExternal(url:string){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';document.body.appendChild(a);a.click();a.remove();}
    async sendFeedback(){const st=el<HTMLDivElement>('feedbackStatus'),message=el<HTMLTextAreaElement>('feedbackMessage').value.trim();if(!message){st.textContent='Write a message first.';return;}const cfg=releaseConfig(),endpoint=safeSameOriginEndpoint(cfg.feedbackEndpoint),fallback=safeHttpsUrl(cfg.feedbackUrl),payload={version:APP_VERSION,type:el<HTMLSelectElement>('feedbackType').value,message:message.slice(0,6000),contact:el<HTMLInputElement>('feedbackContact').value.trim().slice(0,200),technical:el<HTMLInputElement>('feedbackTechnical').checked?{browser:navigator.userAgent.slice(0,500),graphics:this.graphicsQuality.value}:undefined};if(endpoint){st.textContent='Sending…';try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),8000),res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),credentials:'omit',referrerPolicy:'no-referrer',signal:ctrl.signal});clearTimeout(timer);if(!res.ok)throw new Error(`Feedback server returned ${res.status}.`);st.textContent='Feedback sent. Thank you.';el<HTMLTextAreaElement>('feedbackMessage').value='';return;}catch(err){st.textContent=`Could not send directly: ${String((err as Error).message||err)}`;}}
      try{await this.copyText(this.configureFeedbackText());if(fallback){this.openExternal(fallback);st.textContent='Feedback copied; the feedback page was opened in a new tab. Paste the copied text there.';}else st.textContent='Feedback copied. No feedback destination is configured in this build.';}catch(err){st.textContent=String((err as Error).message||err);}}
    openSupport(){const url=safeHttpsUrl(releaseConfig().supportUrl);if(!url){this.setStatus('Support link is not configured.');return;}this.openExternal(url);}
    validateProjectData(m:any){if(!m||typeof m!=='object'||m.format!=='PZOnlineDecorationTool')throw new Error('Not a PZ Online Decoration Tool JSON file.');const w=Number(m.width),h=Number(m.height);if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>600||h>600)throw new Error('Invalid map dimensions.');if(m.layers!==undefined&&!Array.isArray(m.layers))throw new Error('Invalid layer data.');if(Array.isArray(m.layers)&&m.layers.length>256)throw new Error('Project contains too many layers.');let spriteCount=0;if(m.baseStacks!==undefined&&!Array.isArray(m.baseStacks))throw new Error('Invalid base stack data.');for(const lev of m.baseStacks||[]){if(!Array.isArray(lev)||lev.length!==2||!Number.isInteger(+lev[0])||+lev[0]<-64||+lev[0]>64||!Array.isArray(lev[1]))throw new Error('Invalid base stack level.');if(lev[1].length>w*h)throw new Error('Base stack contains too many occupied cells.');for(const cell of lev[1]){if(!Array.isArray(cell)||cell.length!==2||!Number.isInteger(+cell[0])||+cell[0]<0||+cell[0]>=w*h||!Array.isArray(cell[1])||cell[1].length>128)throw new Error('Invalid base stack cell.');for(const n of cell[1]){if(typeof n!=='string'||n.length>512)throw new Error('Invalid sprite name.');spriteCount++;if(spriteCount>8000000)throw new Error('Project contains too many sprites.');}}}
      for(const layer of m.layers||[]){if(!layer||typeof layer!=='object'||typeof layer.name!=='string'||layer.name.length>128||!Number.isInteger(+(layer.level??0))||+(layer.level??0)<-64||+(layer.level??0)>64||!Array.isArray(layer.cells)||layer.cells.length>w*h)throw new Error('Invalid layer.');for(const cell of layer.cells){if(!Array.isArray(cell)||cell.length!==2||!Number.isInteger(+cell[0])||+cell[0]<0||+cell[0]>=w*h||typeof cell[1]!=='string'||cell[1].length>512)throw new Error('Invalid layer cell.');}}}

    setPerformanceStats(enabled:boolean){this.performanceStatsBox.classList.toggle('hidden',!enabled);this.renderer.setPerformanceStats(enabled,s=>this.updatePerformanceStats(s));if(enabled)this.updatePerformanceStats(this.renderer.performanceStats());}
    updatePerformanceStats(s:PerformanceStats){this.performanceStatsBox.textContent=`FPS              ${s.fps.toFixed(1)}\nFrame time       ${s.frameMs.toFixed(2)} ms\nVisible chunks   ${s.visibleChunks} / ${s.totalChunks}\nVisible sprites  ${s.visibleSprites.toLocaleString()}\nDraw calls       ${s.drawCalls.toLocaleString()}\nGPU textures     ${s.activeTextures.toLocaleString()}\nCached batches   ${s.cachedChunkBatches.toLocaleString()}\nDirty chunks     ${s.dirtyChunks}`;}


  }
  addEventListener('DOMContentLoaded',()=>{try{(window as any).pzOnlineDecorationTool=new App();}catch(e){console.error(e);const s=document.getElementById('status');if(s)s.textContent=`Startup error: ${String((e as Error).message||e)}`;}});
}
