/*
 * PZ Online Decoration Tool
 * Copyright (C) 2026 PZ Online Decoration Tool contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
namespace PZODT {
  const APP_VERSION='1.2.0';
  type ReleaseConfig={supportUrl?:string};
  const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
  const storeGet=(k:string):string|null=>{try{return localStorage.getItem(k);}catch{return null;}};
  const storeSet=(k:string,v:string):void=>{try{localStorage.setItem(k,v);}catch{}};
  const releaseConfig=():ReleaseConfig=>{const x=(window as any).PZODT_RELEASE_CONFIG;return x&&typeof x==='object'?x:{};};
  const safeHttpsUrl=(value:unknown):string=>{if(typeof value!=='string'||!value.trim())return '';try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}};
  const safeSupportUrl=(value:unknown):string=>{const href=safeHttpsUrl(value);if(!href)return '';const host=new URL(href).hostname.toLowerCase();return host==='buymeacoffee.com'||host.endsWith('.buymeacoffee.com')?href:'';};
  const save=(name:string,blob:Blob)=>{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  export class App{
    map=new PZMapModel(64,64);assets=new AssetManager();tileDefs=new TileDefDatabase();catalog=new CatalogManager(this.assets,this.tileDefs);importer=new PZWorldImportManager();history=new History();camera:Camera={panX:0,panY:0,zoom:.72};filters=new Map<ViewCategory,boolean>(VIEW_CATEGORIES.map(c=>[c,true]));classificationCache=new Map<string,ViewCategory>();
    renderer:WebGLMapRenderer;editor:EditorController;mediaReadySignature='';selectedFurnitureHit:FurnitureHit|null=null;tileToken=0;furnitureToken=0;furnitureObserver:IntersectionObserver|null=null;heightPresets:PlacementHeightPreset[]=[{label:'Floor',height:0,count:0}];
    pendingEraseCandidates:PickCandidate[]=[];
    status=el<HTMLSpanElement>('status');coords=el<HTMLSpanElement>('coords');tileList=el<HTMLDivElement>('tileList');furnitureList=el<HTMLDivElement>('furnitureList');tileSearch=el<HTMLInputElement>('tileSearch');furnitureSearch=el<HTMLInputElement>('furnitureSearch');tilesetSelect=el<HTMLSelectElement>('tilesetSelect');furnitureCategory=el<HTMLSelectElement>('furnitureCategory');availableOnly=el<HTMLInputElement>('availableOnly');assetSummary=el<HTMLDivElement>('assetSummary');preview=el<HTMLCanvasElement>('previewCanvas');selectionInfo=el<HTMLDivElement>('selectionInfo');orientationButtons=el<HTMLDivElement>('orientationButtons');placementHeightControls=el<HTMLDivElement>('placementHeightControls');selectionLabel=el<HTMLSpanElement>('selectionLabel');zLevel=el<HTMLSelectElement>('zLevel');stageBadge=el<HTMLDivElement>('stageBadge');graphicsQuality=el<HTMLSelectElement>('graphicsQuality');performanceStatsToggle=el<HTMLInputElement>('performanceStatsToggle');performanceStatsBox=el<HTMLDivElement>('performanceStats');nightModeToggle=el<HTMLInputElement>('nightModeToggle');
    constructor(){this.renderer=new WebGLMapRenderer(el('glCanvas'),el('overlayCanvas'),this.assets,()=>this.map,this.camera,n=>this.classify(n),c=>this.filters.get(c)!==false,n=>this.tileDefs.surfaceInfo(n));this.editor=new EditorController(this.renderer,()=>this.map,this.catalog,n=>this.classify(n),n=>this.objectVisible(n),this.history);this.editor.onStatus=s=>this.setStatus(s);this.editor.onChanged=()=>this.mapChanged();this.editor.onSelection=()=>this.selectionChanged();this.editor.onPickCandidates=(items,p)=>this.showPickerChoices(items,p);this.editor.onEraseCandidates=(items,p)=>this.showEraseChoices(items,p);this.assets.onChanged=()=>this.assetsChanged();this.bind();this.updateLoadMode();this.updateMediaUi('needed');this.renderFilterButtons();this.renderFurnitureCategories();this.refreshAll();const saved=storeGet('pzodt.graphicsQuality'),q:GraphicsQuality=saved==='low'||saved==='medium'||saved==='high'?saved:'high';this.graphicsQuality.value=q;this.renderer.setQuality(q);const perf=storeGet('pzodt.performanceStats')==='1';this.performanceStatsToggle.checked=perf;this.setPerformanceStats(perf);const night=storeGet('pzodt.nightMode')!=='0';this.nightModeToggle.checked=night;this.applyNightMode(night,false);setTimeout(()=>this.renderer.center(),50);this.configureRelease();}
    classify(n:string):ViewCategory{let c=this.classificationCache.get(n);if(c)return c;c=this.tileDefs.classify(n,this.catalog.furnitureTiles);this.classificationCache.set(n,c);return c;}
    objectVisible(n:string):boolean{return this.filters.get(this.classify(n))!==false;}
    setStatus(s:string){this.status.textContent=s;}
    updateMediaUi(state:'needed'|'indexing'|'ready'|'error',message=''){const ready=state==='ready',busy=state==='indexing',datasets=el<HTMLSelectElement>('datasetSelect').options.length&&!!el<HTMLSelectElement>('datasetSelect').value;document.body.classList.toggle('mediaNeeded',!ready);const choose=el<HTMLButtonElement>('chooseMediaBtn'),noticeChoose=el<HTMLButtonElement>('mediaNoticeChooseBtn'),loadWorld=el<HTMLButtonElement>('loadLocationBtn'),load=el<HTMLButtonElement>('loadBtn'),notice=el<HTMLSpanElement>('mediaNoticeText'),loadStatus=el<HTMLDivElement>('loadStatus');choose.disabled=busy;noticeChoose.disabled=busy;choose.textContent=ready?'Change Media Folder…':busy?'Indexing Media…':'Choose Media Folder…';loadWorld.disabled=!ready||!datasets;load.disabled=!ready||!datasets;if(message){notice.textContent=message;loadStatus.textContent=message;}else if(state==='needed'){notice.textContent='Please choose the Project Zomboid Media folder to load tiles and furniture.';loadStatus.textContent='Choose the media folder from the main toolbar first.';}else if(ready){loadStatus.textContent=datasets?'Media library ready. Enter coordinates and load a location.':'Media library ready, but no map dataset was found.';}}
    bind(){document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>this.editor.setTool(b.dataset.tool as ToolName));document.querySelectorAll<HTMLButtonElement>('.tab').forEach(b=>b.onclick=()=>this.setTab(b.dataset.tab==='furniture'?'furniture':'tiles'));
      el<HTMLButtonElement>('rotateBtn').onclick=()=>this.editor.rotateFurniture(1);el<HTMLButtonElement>('undoBtn').onclick=()=>this.editor.undo();el<HTMLButtonElement>('redoBtn').onclick=()=>this.editor.redo();
      el<HTMLButtonElement>('newMapBtn').onclick=()=>this.newMap();el<HTMLButtonElement>('chooseMediaBtn').onclick=()=>el<HTMLInputElement>('mediaInput').click();el<HTMLButtonElement>('mediaNoticeChooseBtn').onclick=()=>el<HTMLInputElement>('mediaInput').click();el<HTMLButtonElement>('loadLocationBtn').onclick=()=>this.openLoadDialog();el<HTMLButtonElement>('saveJsonBtn').onclick=()=>save('pz-online-decoration.json',new Blob([JSON.stringify({map:this.map.toJSON(),filters:Object.fromEntries(this.filters)})],{type:'application/json'}));el<HTMLButtonElement>('openJsonBtn').onclick=()=>el<HTMLInputElement>('jsonInput').click();
      el<HTMLButtonElement>('settingsBtn').onclick=()=>el<HTMLDialogElement>('settingsDialog').showModal();el<HTMLButtonElement>('settingsCloseBtn').onclick=el<HTMLButtonElement>('settingsDoneBtn').onclick=()=>el<HTMLDialogElement>('settingsDialog').close();this.graphicsQuality.onchange=()=>{const q=this.graphicsQuality.value as GraphicsQuality;storeSet('pzodt.graphicsQuality',q);this.renderer.setQuality(q);setTimeout(()=>this.renderer.center(),0);this.setStatus(`Graphics: ${q}.`);};this.performanceStatsToggle.onchange=()=>{storeSet('pzodt.performanceStats',this.performanceStatsToggle.checked?'1':'0');this.setPerformanceStats(this.performanceStatsToggle.checked);};
      el<HTMLButtonElement>('creditsBtn').onclick=()=>{el<HTMLDialogElement>('settingsDialog').close();el<HTMLDialogElement>('creditsDialog').showModal();};el<HTMLButtonElement>('creditsCloseBtn').onclick=el<HTMLButtonElement>('creditsDoneBtn').onclick=()=>el<HTMLDialogElement>('creditsDialog').close();el<HTMLButtonElement>('feedbackBtn').onclick=()=>this.openFeedbackDialog();this.nightModeToggle.onchange=()=>this.applyNightMode(this.nightModeToggle.checked,true);el<HTMLButtonElement>('feedbackCloseBtn').onclick=()=>el<HTMLDialogElement>('feedbackDialog').close();el<HTMLButtonElement>('supportBtn').onclick=()=>this.openSupport();
      document.querySelectorAll<HTMLFormElement>('dialog form').forEach(f=>f.addEventListener('submit',e=>e.preventDefault()));
      el<HTMLButtonElement>('collapseLeftBtn').onclick=()=>this.collapse('left',true);el<HTMLButtonElement>('openLeftPanelBtn').onclick=()=>this.collapse('left',false);el<HTMLButtonElement>('collapseRightBtn').onclick=()=>this.collapse('right',true);el<HTMLButtonElement>('openRightPanelBtn').onclick=()=>this.collapse('right',false);
      this.tileSearch.oninput=()=>this.renderTiles();this.tilesetSelect.onchange=()=>this.renderTiles();this.furnitureSearch.oninput=()=>this.renderFurniture();this.furnitureCategory.onchange=()=>this.renderFurniture();this.availableOnly.onchange=()=>this.renderFurniture();
      this.zLevel.onchange=()=>this.setZLevel(+this.zLevel.value);el<HTMLButtonElement>('zDownBtn').onclick=()=>this.stepZ(-1);el<HTMLButtonElement>('zUpBtn').onclick=()=>this.stepZ(1);el<HTMLButtonElement>('addLevelBtn').onclick=()=>this.setZLevel(this.map.maxLevel()+1);
      el<HTMLButtonElement>('loadCancelBtn').onclick=()=>el<HTMLDialogElement>('loadDialog').close();el<HTMLSelectElement>('loadMode').onchange=()=>this.updateLoadMode();el<HTMLSelectElement>('datasetSelect').onchange=()=>this.updateMediaUi(this.mediaReadySignature?'ready':'needed');el<HTMLButtonElement>('loadBtn').onclick=()=>this.loadLocation();el<HTMLButtonElement>('versionHistoryBtn').onclick=()=>el<HTMLDialogElement>('versionHistoryDialog').showModal();el<HTMLButtonElement>('versionHistoryCloseBtn').onclick=()=>el<HTMLDialogElement>('versionHistoryDialog').close();
      el<HTMLButtonElement>('pickerCloseBtn').onclick=el<HTMLButtonElement>('pickerCancelBtn').onclick=()=>el<HTMLDialogElement>('pickerDialog').close();el<HTMLButtonElement>('eraseCloseBtn').onclick=el<HTMLButtonElement>('eraseCancelBtn').onclick=()=>el<HTMLDialogElement>('eraseDialog').close();el<HTMLButtonElement>('eraseSelectedBtn').onclick=()=>this.confirmEraseSelection();
      el<HTMLInputElement>('mediaInput').onchange=e=>this.mediaSelected(e);el<HTMLInputElement>('jsonInput').onchange=e=>this.jsonSelected(e);
      this.renderer.overlay.addEventListener('pointermove',e=>{const r=this.renderer.overlay.getBoundingClientRect(),p=this.renderer.screenToTile(e.clientX-r.left,e.clientY-r.top,this.map.currentLevel),ox=Number(this.map.properties['pzodt.worldOriginX']),oy=Number(this.map.properties['pzodt.worldOriginY']);this.coords.textContent=Number.isFinite(ox)&&Number.isFinite(oy)?`local ${p.x},${p.y} · world ${ox+p.x},${oy+p.y},${this.map.currentLevel}`:`x ${p.x} · y ${p.y} · Z ${this.map.currentLevel}`;});
    }
    openLoadDialog(){if(!this.mediaReadySignature){this.updateMediaUi('needed','Please choose the Project Zomboid Media folder before loading a world location.');return;}const d=el<HTMLDialogElement>('loadDialog');this.updateLoadMode();this.updateMediaUi('ready');if(!d.open)d.showModal();}
    private candidateWorld(item:PickCandidate){const ox=Number(this.map.properties['pzodt.worldOriginX']),oy=Number(this.map.properties['pzodt.worldOriginY']);return{x:(Number.isFinite(ox)?ox:0)+item.x,y:(Number.isFinite(oy)?oy:0)+item.y};}
    private drawCandidatePreview(c:HTMLCanvasElement,item:PickCandidate){const w=this.candidateWorld(item);return this.assets.drawPreview(c,item.name,w.x,w.y);}
    showPickerChoices(items:PickCandidate[],p:{x:number;y:number}){const box=el<HTMLDivElement>('pickerChoices');box.replaceChildren();el<HTMLDivElement>('pickerInfo').textContent=`${items.length} objects at ${p.x}, ${p.y}, Z ${this.map.currentLevel}.`;const seen=new Set<string>();for(const item of items){const matches=this.catalog.matchesTile(item.name,false);for(const match of matches){const key=`${match.groupIndex}:${match.furnitureIndex}:${match.orient}:${item.targetId}`;if(seen.has(key))continue;seen.add(key);const group=document.createElement('div');group.className='pickerGroup';const parent=document.createElement('button');parent.type='button';parent.className='pickerChoice pickerFurnitureChoice';const pc=document.createElement('canvas');pc.width=68;pc.height=64;const pt=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');title.textContent=`${match.group.label} · #${match.def.index}`;meta.textContent=`Furniture object · appearance ${Math.max(0,match.def.entries.findIndex(e=>e.orient===match.orient))+1} · ${this.catalog.entry(match.def,match.orient)?.cells.length??0} tile(s)`;pt.append(title,meta);parent.append(pc,pt);parent.onclick=()=>{this.selectedFurnitureHit=this.furnitureHitFromMatch(match);this.editor.applyPickFurniture(match,item);el<HTMLDialogElement>('pickerDialog').close();};group.appendChild(parent);this.drawFurniture(pc,match.def,match.orient).catch(()=>{});box.appendChild(group);}if(matches.length)continue;const b=document.createElement('button');b.type='button';b.className='pickerChoice';const cv=document.createElement('canvas');cv.width=68;cv.height=64;const text=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');title.textContent=item.name;meta.textContent=`${item.sourceLabel} · ${item.category}`;text.append(title,meta);b.append(cv,text);b.onclick=()=>{this.editor.applyPickCandidate(item);el<HTMLDialogElement>('pickerDialog').close();};box.appendChild(b);this.drawCandidatePreview(cv,item).catch(()=>{});}const d=el<HTMLDialogElement>('pickerDialog');if(!d.open)d.showModal();}
    showEraseChoices(items:PickCandidate[],p:{x:number;y:number}){this.pendingEraseCandidates=items;const box=el<HTMLDivElement>('eraseChoices');box.replaceChildren();el<HTMLDivElement>('eraseInfo').textContent=`Choose one or more objects to erase at ${p.x}, ${p.y}, Z ${this.map.currentLevel}.`;const confirm=el<HTMLButtonElement>('eraseSelectedBtn');confirm.disabled=true;items.forEach((item,i)=>{const row=document.createElement('label');row.className='eraseChoice';const check=document.createElement('input');check.type='checkbox';check.value=String(i);check.onchange=()=>{confirm.disabled=!box.querySelector<HTMLInputElement>('input[type=checkbox]:checked');};const cv=document.createElement('canvas');cv.width=68;cv.height=64;const text=document.createElement('span'),title=document.createElement('b'),meta=document.createElement('small');const match=this.catalog.matchesTile(item.name,false)[0];title.textContent=match?this.catalog.displayName(match.def,match.group):item.name;meta.textContent=match?`${item.name} · ${item.sourceLabel} · ${item.category}`:`${item.sourceLabel} · ${item.category}`;text.append(title,meta);row.append(check,cv,text);box.appendChild(row);this.drawCandidatePreview(cv,item).catch(()=>{});});const d=el<HTMLDialogElement>('eraseDialog');if(!d.open)d.showModal();}
    confirmEraseSelection(){const box=el<HTMLDivElement>('eraseChoices'),selected=[...box.querySelectorAll<HTMLInputElement>('input[type=checkbox]:checked')].map(x=>this.pendingEraseCandidates[+x.value]).filter((x):x is PickCandidate=>!!x);if(!selected.length)return;this.editor.eraseCandidates(selected);this.pendingEraseCandidates=[];el<HTMLDialogElement>('eraseDialog').close();}

    private furnitureHitFromMatch(match:FurnitureTileMatch):FurnitureHit{const seen=new Set<string>();let total=0,available=0;for(const e of match.def.entries)for(const cell of e.cells){const name=cell[2];if(seen.has(name))continue;seen.add(name);total++;if(this.assets.asset(name))available++;}return{group:match.group,def:match.def,groupIndex:match.groupIndex,furnitureIndex:match.furnitureIndex,available,total};}
    collapse(side:'left'|'right',yes:boolean){const l=document.querySelector<HTMLElement>('.layout')!;l.classList.toggle(`${side}-collapsed`,yes);el<HTMLButtonElement>(side==='left'?'openLeftPanelBtn':'openRightPanelBtn').classList.toggle('hidden',!yes);setTimeout(()=>{this.renderer.resize();this.renderer.request();},0);}
    setTab(t:'tiles'|'furniture'){document.querySelectorAll<HTMLElement>('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===t));el('tilesTab').classList.toggle('active',t==='tiles');el('furnitureTab').classList.toggle('active',t==='furniture');t==='tiles'?this.renderTiles():this.renderFurniture();}
    newMap(){if((this.map.layers.some(l=>l.cells.size)||[...this.map.baseStacks.values()].some(m=>m.size))&&!confirm('Start a new map? Unsaved edits will be lost.'))return;this.map=new PZMapModel(64,64);this.history=new History();(this.editor as any).history=this.history;this.renderer.mapReplaced();this.refreshAll();this.renderer.center();}
    async mediaSelected(e:Event){const inp=e.target as HTMLInputElement;if(!inp.files?.length)return;if(inp.files.length>100000){this.setStatus('Media folder contains too many files to index safely.');this.updateMediaUi('error','The selected folder contains too many files to index safely.');inp.value='';return;}const oldSignature=this.mediaReadySignature,list=this.importer.scan(inp.files),select=el<HTMLSelectElement>('datasetSelect');if(this.importer.selectedBytes()>16*1024*1024*1024){this.updateMediaUi('error','The selected media folder is too large to index safely in a browser session.');this.setStatus('Media folder is too large to index safely.');inp.value='';return;}select.replaceChildren();for(const d of list){const o=document.createElement('option');o.value=d.id;o.textContent=`${d.label} · ${d.headers} headers / ${d.packs} lotpacks`;select.appendChild(o);}if(!list.length){const o=document.createElement('option');o.value='';o.textContent='No map dataset found';select.appendChild(o);}if(oldSignature&&oldSignature!==this.importer.mediaSignature){this.assets.clear();this.tileDefs.clear();this.classificationCache.clear();this.mediaReadySignature='';}const found=`${this.importer.assetFiles().length} texture source file(s) · ${this.importer.tileDefFiles().length} .tiles definition file(s)`;this.updateMediaUi('indexing',`Media folder selected. Indexing ${found}…`);inp.value='';try{let lastProgress=0;const progress=(s:string)=>{const now=performance.now(),important=/ready|error|already indexed/i.test(s);if(!important&&now-lastProgress<60)return;lastProgress=now;el<HTMLSpanElement>('mediaNoticeText').textContent=s;el<HTMLDivElement>('loadStatus').textContent=s;this.setStatus(s);};await this.ensureMediaReady(progress);this.renderTilesets();this.renderTiles();this.renderFurnitureCategories();this.renderFurniture();this.selectionChanged();const msg=`Media ready: ${this.assets.assets.size.toLocaleString()} sprites · ${this.tileDefs.props.size.toLocaleString()} tile definitions${list.length?` · ${list.length} map dataset(s)`:' · no map dataset found'}.`;this.updateMediaUi('ready');this.setStatus(msg);}catch(err){const msg=`Media error: ${String((err as Error).message||err)}`;console.error(err);this.updateMediaUi('error',msg);this.setStatus(msg);}}
    updateLoadMode(){const m=el<HTMLSelectElement>('loadMode').value;el('marginRow').classList.toggle('hidden',m!=='building');el('areaRow').classList.toggle('hidden',m!=='area');}
    async ensureMediaReady(progress:(s:string)=>void){if(this.mediaReadySignature===this.importer.mediaSignature&&this.mediaReadySignature){progress('Media library already indexed — reusing cached tiles, .pack textures and .tiles properties.');return;}progress('Indexing local media assets…');const defs=this.tileDefs.loadFiles(this.importer.tileDefFiles(),progress),expected=defs.then(()=>(name:string)=>this.tileDefs.tilesetCount(name)),assets=this.assets.loadMediaFiles(this.importer.assetFiles(),progress,expected),[a,props]=await Promise.all([assets,defs]);this.classificationCache.clear();this.refreshHeightPresets();this.renderer.invalidateAllGeometry();this.mediaReadySignature=this.importer.mediaSignature;progress(`Media ready: ${this.assets.assets.size.toLocaleString()} sprites · ${props.toLocaleString()} property-bearing tile definitions${a.pngSkipped?` · ${a.pngSkipped.toLocaleString()} duplicate PNG sheet(s) skipped`:''}${a.skipped?` · ${a.skipped} cached files skipped`:''}.`);}

    async loadLocation(){const ds=el<HTMLSelectElement>('datasetSelect').value,x=+el<HTMLInputElement>('worldX').value,y=+el<HTMLInputElement>('worldY').value,mode=el<HTMLSelectElement>('loadMode').value as PZImportMode,margin=+el<HTMLInputElement>('marginInput').value,aw=+el<HTMLInputElement>('areaW').value,ah=+el<HTMLInputElement>('areaH').value,st=el<HTMLDivElement>('loadStatus'),btn=el<HTMLButtonElement>('loadBtn');if(!this.mediaReadySignature){st.textContent='Choose and finish indexing the media folder first.';return;}if(!ds||!Number.isFinite(x)||!Number.isFinite(y)){st.textContent='Select a map dataset and enter valid World X / Y.';return;}btn.disabled=true;try{const progress=(s:string)=>{st.textContent=s;this.setStatus(s);};await this.ensureMediaReady(progress);const r=await this.importer.importLocation({datasetId:ds,x:Math.round(x),y:Math.round(y),mode,margin:Math.max(0,margin|0),areaWidth:Math.max(1,aw|0),areaHeight:Math.max(1,ah|0)},progress);this.map=r.map;this.history=new History();this.renderer.mapReplaced();(this.editor as any).history=this.history;this.refreshAll();this.renderer.center();const missing=[...r.usedTiles].filter(n=>!this.assets.asset(n));const msg=`Loaded ${r.buildingName||mode}: ${r.bounds.w}×${r.bounds.h}, ${r.importedSprites.toLocaleString()} sprites${missing.length?` · ${missing.length.toLocaleString()} texture(s) unresolved`:''}.`;this.setStatus(msg);st.textContent=msg;el<HTMLDialogElement>('loadDialog').close();}catch(err){const msg=`Load error: ${String((err as Error).message||err)}`;console.error(err);st.textContent=msg;this.setStatus(msg);}finally{btn.disabled=false;}}
    async jsonSelected(e:Event){const inp=e.target as HTMLInputElement,f=inp.files?.[0];if(!f)return;try{if(f.size>64*1024*1024)throw new Error('JSON project is larger than the 64 MiB safety limit.');const o=JSON.parse(await f.text()),m=o?.map??o;this.validateProjectData(m);this.map=PZMapModel.fromJSON(m);this.renderer.mapReplaced();if(o&&typeof o==='object'&&o.filters)for(const c of VIEW_CATEGORIES)this.filters.set(c,o.filters[c]!==false);this.history=new History();(this.editor as any).history=this.history;this.refreshAll();this.renderer.center();this.setStatus('JSON project opened. Load the same media folder if textures are not currently indexed.');}catch(err){this.setStatus(`JSON error: ${String((err as Error).message||err)}`);}inp.value='';}
    renderFilterButtons(){const box=el<HTMLDivElement>('viewFilters');box.replaceChildren();for(const c of VIEW_CATEGORIES){const b=document.createElement('button');b.className='viewFilter';b.textContent=c;b.onclick=()=>{const v=this.filters.get(c)!;this.filters.set(c,!v);b.classList.toggle('off',v);this.renderer.request();};box.appendChild(b);}}
    refreshAll(){this.renderLevels();this.renderTilesets();this.renderTiles();this.renderFurnitureCategories();this.renderFurniture();this.selectionChanged();this.renderFilterState();this.renderer.request();}
    mapChanged(){this.renderLevels();this.renderer.request();}
    assetsChanged(){this.classificationCache.clear();this.renderer.assetsChanged();this.renderTilesets();this.renderTiles();this.renderFurniture();this.selectionChanged();this.renderer.request();}
    renderFilterState(){const box=el('viewFilters');[...box.querySelectorAll<HTMLButtonElement>('.viewFilter')].forEach(b=>b.classList.toggle('off',this.filters.get(b.textContent as ViewCategory)===false));}
    setZLevel(z:number){this.map.currentLevel=z;this.renderLevels();this.editor.refreshPlacementGhost();this.renderer.request();}
    stepZ(delta:number){const levels=this.map.levels().sort((a,b)=>a-b),i=levels.indexOf(this.map.currentLevel),j=Math.max(0,Math.min(levels.length-1,(i<0?0:i)+delta));if(levels[j]!==undefined)this.setZLevel(levels[j]);}
    updateZButtons(){const levels=this.map.levels().sort((a,b)=>a-b),i=levels.indexOf(this.map.currentLevel);el<HTMLButtonElement>('zDownBtn').disabled=i<=0;el<HTMLButtonElement>('zUpBtn').disabled=i<0||i>=levels.length-1;}
    renderLevels(){const ls=this.map.levels();if(!ls.includes(this.map.currentLevel))ls.push(this.map.currentLevel);ls.sort((a,b)=>a-b);this.zLevel.replaceChildren();for(const z of ls){const o=document.createElement('option');o.value=String(z);o.textContent=`Z ${z}`;this.zLevel.appendChild(o);}this.zLevel.value=String(this.map.currentLevel);const z=this.map.currentLevel;this.stageBadge.textContent=z===0?'Z 0 · ground editing plane':z>0?`Z ${z} · elevated editing plane`:`Z ${z} · lower editing plane`;this.updateZButtons();}
    renderTilesets(){const old=this.tilesetSelect.value;this.tilesetSelect.replaceChildren();const all=document.createElement('option');all.value='';all.textContent='All tilesets';this.tilesetSelect.appendChild(all);for(const n of this.assets.tilesetNames()){const o=document.createElement('option');o.value=n;o.textContent=n;this.tilesetSelect.appendChild(o);}if([...this.tilesetSelect.options].some(o=>o.value===old))this.tilesetSelect.value=old;this.assetSummary.textContent=this.assets.assets.size?`${this.assets.assets.size.toLocaleString()} sprites · ${this.tileDefs.props.size.toLocaleString()} tile definitions`:'Choose the Project Zomboid media folder to index the media library.';}
    renderTiles(){const token=++this.tileToken;this.tileList.replaceChildren();const q=this.tileSearch.value;let a=this.tilesetSelect.value?this.assets.assetsForTileset(this.tilesetSelect.value):this.assets.search(q,500,x=>this.tileDefs.searchText(x.name));if(this.tilesetSelect.value&&q.trim())a=a.filter(x=>searchMatches(`${x.name} ${this.tileDefs.searchText(x.name)}`,q));const f=document.createDocumentFragment();for(const x of a.slice(0,500)){const d=document.createElement('div');d.className='tilecard'+(this.editor.selectedAsset===x.name?' selected':'');const c=document.createElement('canvas');c.width=90;c.height=82;const n=document.createElement('div');n.className='name';const friendly=this.tileDefs.displayName(x.name);n.textContent=friendly!==x.name?`${friendly} · ${x.name}`:x.name;n.title=this.tileDefs.searchText(x.name);d.append(c,n);d.onclick=()=>{this.editor.selectAsset(x.name);this.renderTiles();};f.appendChild(d);this.assets.drawPreview(c,x.name).catch(()=>{});}if(token===this.tileToken)this.tileList.appendChild(f);}
    renderFurnitureCategories(){const old=this.furnitureCategory.value;this.furnitureCategory.replaceChildren();const all=document.createElement('option');all.value='';all.textContent='All furniture categories';this.furnitureCategory.appendChild(all);for(const c of this.catalog.categories()){const o=document.createElement('option');o.value=c;o.textContent=c;this.furnitureCategory.appendChild(o);}if([...this.furnitureCategory.options].some(o=>o.value===old))this.furnitureCategory.value=old;}
    renderFurniture(){const token=++this.furnitureToken;this.furnitureList.replaceChildren();const hits=this.catalog.search(this.furnitureSearch.value,this.furnitureCategory.value,300).filter(h=>!this.availableOnly.checked||h.available===h.total);if(!hits.length){const empty=document.createElement('div');empty.className='hint';empty.textContent='No matching available furniture.';this.furnitureList.appendChild(empty);return;}const f=document.createDocumentFragment(),previews:Array<{c:HTMLCanvasElement;h:FurnitureHit}>=[];for(const h of hits){const d=document.createElement('div');d.className='furnitureitem'+(this.selectedFurnitureHit?.groupIndex===h.groupIndex&&this.selectedFurnitureHit?.furnitureIndex===h.furnitureIndex?' selected':'');const c=document.createElement('canvas');c.className='furniturethumb';c.width=78;c.height=72;const t=document.createElement('div');t.className='furnituretext';const title=document.createElement('b'),friendly=this.catalog.displayName(h.def,h.group);title.textContent=friendly;title.title=`${h.group.label} · #${h.def.index}`;const meta=document.createElement('small');meta.textContent=`${h.group.label} · #${h.def.index} · ${h.def.entries.length} alternative appearance${h.def.entries.length===1?'':'s'} · ${h.available}/${h.total} tiles`;t.append(title,meta);d.append(c,t);d.onclick=()=>{this.selectedFurnitureHit=h;this.editor.selectFurniture(h.def);this.renderFurniture();};f.appendChild(d);previews.push({c,h});}this.furnitureList.appendChild(f);this.furnitureObserver?.disconnect();this.furnitureObserver=new IntersectionObserver(es=>{for(const e of es)if(e.isIntersecting){const q=previews.find(x=>x.c===e.target);if(q){this.furnitureObserver?.unobserve(q.c);this.drawFurniture(q.c,q.h.def,q.h.def.entries[0]?.orient||'N',()=>token===this.furnitureToken&&q.c.isConnected).catch(()=>{});}}},{root:this.furnitureList,rootMargin:'120px'});for(const q of previews)this.furnitureObserver.observe(q.c);}
    selectionChanged(){document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===this.editor.tool));this.renderSelection();}

    private refreshHeightPresets(){const values=this.tileDefs.placementHeightValues(5);this.heightPresets=[{label:'H0',height:0,count:0},...values.map(v=>({label:`H${v.height}`,height:v.height,count:v.count}))];}
    private renderPlacementHeights(){this.placementHeightControls.replaceChildren();if(!this.editor.selectedAsset&&!this.editor.selectedFurniture)return;const title=document.createElement('div');title.className='placementHeightTitle';title.textContent='Placement height';const hint=document.createElement('div');hint.className='placementHeightHint';hint.textContent="Adjust the object's placement height here. Use + / − on the keyboard for fine adjustment.";this.placementHeightControls.append(title,hint);const buttons=document.createElement('div');buttons.className='placementHeightButtons';for(const p of this.heightPresets){const b=document.createElement('button');b.type='button';b.textContent=`H${p.height}`;b.title=p.count?`Common height found in ${p.count} surface definitions from the loaded media`:'Floor height';b.classList.toggle('active',this.editor.placementHeight===p.height);b.onclick=()=>this.editor.setPlacementHeight(p.height);buttons.appendChild(b);}this.placementHeightControls.appendChild(buttons);const custom=document.createElement('div');custom.className='placementHeightCustom';const minus=document.createElement('button');minus.type='button';minus.textContent='−';minus.title='Decrease placement height (-)';minus.onclick=()=>this.editor.setPlacementHeight(this.editor.placementHeight-1);const input=document.createElement('input');input.type='number';input.min='0';input.max='128';input.step='1';input.value=String(this.editor.placementHeight);input.setAttribute('aria-label','Custom placement height');const apply=()=>this.editor.setPlacementHeight(+input.value);input.onchange=apply;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();apply();}};const plus=document.createElement('button');plus.type='button';plus.textContent='+';plus.title='Increase placement height (+)';plus.onclick=()=>this.editor.setPlacementHeight(this.editor.placementHeight+1);custom.append(minus,input,plus);this.placementHeightControls.appendChild(custom);}
    async renderSelection(){const ctx=this.preview.getContext('2d')!;ctx.clearRect(0,0,this.preview.width,this.preview.height);this.orientationButtons.replaceChildren();this.renderPlacementHeights();if(this.editor.selectedAsset){this.selectionLabel.textContent=this.editor.selectedAsset;const cat=this.classify(this.editor.selectedAsset),ctx=this.editor.selectedContext;this.selectionInfo.textContent=`${cat}\n${this.editor.selectedAsset}\nHeight: H${this.editor.placementHeight}`;if(ctx){const w=this.candidateWorld(ctx);await this.assets.drawPreview(this.preview,this.editor.selectedAsset,w.x,w.y);}else await this.assets.drawPreview(this.preview,this.editor.selectedAsset);return;}const d=this.editor.selectedFurniture;if(d){let h=this.selectedFurnitureHit;if(!h||h.def!==d){h=this.catalog.search('','',5000).find(x=>x.def===d)??null;this.selectedFurnitureHit=h;}const orientations=this.catalog.orientations(d),appearanceIndex=Math.max(0,orientations.indexOf(this.editor.furnitureOrient)),friendly=this.catalog.displayName(d,h?.group??null);this.selectionLabel.textContent=`${friendly} · Appearance ${appearanceIndex+1}`;this.selectionInfo.textContent=`${friendly}${h?`\n${h.group.label} · #${d.index}`:`\n#${d.index}`}\nHeight: H${this.editor.placementHeight}`;const appearanceLabel=document.createElement('span');appearanceLabel.className='orientationLabel';appearanceLabel.textContent='Alternative appearance';this.orientationButtons.appendChild(appearanceLabel);for(let i=0;i<orientations.length;i++){const o=orientations[i],b=document.createElement('button');b.textContent=String(i+1);b.classList.toggle('active',o===this.editor.furnitureOrient);b.onclick=()=>{this.editor.furnitureOrient=o;this.selectionChanged();};this.orientationButtons.appendChild(b);}await this.drawFurniture(this.preview,d,this.editor.furnitureOrient);return;}this.selectionLabel.textContent='No tile selected';this.selectionInfo.textContent='Nothing selected.';}
    async drawFurniture(c:HTMLCanvasElement,d:FurnitureDef,o:string,guard:()=>boolean=()=>true){const e=this.catalog.entry(d,o);if(!e)return;const parts:Array<any>=[];for(const [dx,dy,n] of e.cells){const a=this.assets.asset(n);if(!a)continue;try{parts.push({a,b:await this.assets.bitmap(a.sourceId),dx,dy});}catch{}}if(!parts.length||!guard())return;const ds=this.assets.dominantScale(),tw=64*ds,th=32*ds;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const loc=parts.map(p=>{const bx=(p.dx-p.dy)*tw/2,by=(p.dx+p.dy)*th/2,s=ds/(p.a.scale||1),fw=p.a.frameW*s,fh=p.a.frameH*s,l=bx-fw/2+p.a.offsetX*s,t=by+th-fh+p.a.offsetY*s,r=l+p.a.sw*s,bb=t+p.a.sh*s;minX=Math.min(minX,l);minY=Math.min(minY,t);maxX=Math.max(maxX,r);maxY=Math.max(maxY,bb);return{...p,l,t,s};}).sort((a,b)=>(a.dx+a.dy)-(b.dx+b.dy)||a.dy-b.dy);const pad=4,w=Math.max(1,maxX-minX),h=Math.max(1,maxY-minY),fit=Math.min((c.width-pad*2)/w,(c.height-pad*2)/h,1),ox=(c.width-w*fit)/2-minX*fit,oy=(c.height-h*fit)/2-minY*fit,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;for(const p of loc){const a=p.a;ctx.drawImage(p.b,a.sx,a.sy,a.sw,a.sh,ox+p.l*fit,oy+p.t*fit,a.sw*p.s*fit,a.sh*p.s*fit);}}
    configureRelease(){const support=safeSupportUrl(releaseConfig().supportUrl);el<HTMLButtonElement>('supportBtn').classList.toggle('hidden',!support);}
    applyNightMode(enabled:boolean,persist=true){this.nightModeToggle.checked=enabled;document.body.classList.toggle('lightMode',!enabled);this.renderer.setNightMode(enabled);if(persist)storeSet('pzodt.nightMode',enabled?'1':'0');}
    openFeedbackDialog(){const frame=el<HTMLIFrameElement>('feedbackFrame');if(!frame.getAttribute('src')){const raw=frame.dataset.src??'';try{const u=new URL(raw,location.href);if(u.protocol==='https:'&&u.hostname==='tally.so')frame.src=u.href;}catch{}}el<HTMLDialogElement>('feedbackDialog').showModal();}
    openExternal(url:string){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';document.body.appendChild(a);a.click();a.remove();}
    openSupport(){const url=safeSupportUrl(releaseConfig().supportUrl);if(!url){this.setStatus('Support link is not configured.');return;}this.openExternal(url);}
    validateProjectData(m:any){
      if(!m||typeof m!=='object'||Array.isArray(m)||m.format!=='PZOnlineDecorationTool')throw new Error('Not a PZ Online Decoration Tool JSON file.');
      const w=Number(m.width),h=Number(m.height),tileWidth=Number(m.tileWidth??64),tileHeight=Number(m.tileHeight??32),levelY=Number(m.cellsPerLevelY??3),currentLevel=Number(m.currentLevel??0);
      if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>600||h>600)throw new Error('Invalid map dimensions.');
      if(!Number.isFinite(tileWidth)||tileWidth<16||tileWidth>512||!Number.isFinite(tileHeight)||tileHeight<8||tileHeight>256||!Number.isFinite(levelY)||levelY<0||levelY>64)throw new Error('Invalid map geometry.');
      if(!Number.isInteger(currentLevel)||currentLevel<-64||currentLevel>64)throw new Error('Invalid current Z level.');
      if(m.properties!==undefined){if(!m.properties||typeof m.properties!=='object'||Array.isArray(m.properties))throw new Error('Invalid project properties.');const entries=Object.entries(m.properties);if(entries.length>64)throw new Error('Project contains too many properties.');for(const [k,v] of entries){if(k.length>128||['__proto__','prototype','constructor'].includes(k)||typeof v!=='string'||v.length>2048)throw new Error('Invalid project property.');}}
      if(m.layers!==undefined&&!Array.isArray(m.layers))throw new Error('Invalid layer data.');
      if(Array.isArray(m.layers)&&m.layers.length>256)throw new Error('Project contains too many layers.');
      if(m.baseStacks!==undefined&&!Array.isArray(m.baseStacks))throw new Error('Invalid base stack data.');
      if(Array.isArray(m.baseStacks)&&m.baseStacks.length>129)throw new Error('Project contains too many Z levels.');
      let spriteCount=0;
      for(const lev of m.baseStacks||[]){if(!Array.isArray(lev)||lev.length!==2||!Number.isInteger(+lev[0])||+lev[0]<-64||+lev[0]>64||!Array.isArray(lev[1]))throw new Error('Invalid base stack level.');if(lev[1].length>w*h)throw new Error('Base stack contains too many occupied cells.');for(const cell of lev[1]){if(!Array.isArray(cell)||cell.length!==2||!Number.isInteger(+cell[0])||+cell[0]<0||+cell[0]>=w*h||!Array.isArray(cell[1])||cell[1].length>128)throw new Error('Invalid base stack cell.');for(const n of cell[1]){if(typeof n!=='string'||n.length<1||n.length>512)throw new Error('Invalid sprite name.');if(++spriteCount>4000000)throw new Error('Project contains too many sprites.');}}}
      const ids=new Set<string>();
      for(const layer of m.layers||[]){if(!layer||typeof layer!=='object'||Array.isArray(layer)||typeof layer.name!=='string'||layer.name.length<1||layer.name.length>128||!Number.isInteger(+(layer.level??0))||+(layer.level??0)<-64||+(layer.level??0)>64||!Array.isArray(layer.cells)||layer.cells.length>w*h)throw new Error('Invalid layer.');if(layer.id!==undefined&&(typeof layer.id!=='string'||layer.id.length<1||layer.id.length>128||ids.has(layer.id)))throw new Error('Invalid layer id.');if(typeof layer.id==='string')ids.add(layer.id);for(const cell of layer.cells){if(!Array.isArray(cell)||cell.length!==2||!Number.isInteger(+cell[0])||+cell[0]<0||+cell[0]>=w*h||typeof cell[1]!=='string'||cell[1].length<1||cell[1].length>512)throw new Error('Invalid layer cell.');if(++spriteCount>4000000)throw new Error('Project contains too many sprites.');}if(layer.placementHeights!==undefined){if(!Array.isArray(layer.placementHeights)||layer.placementHeights.length>w*h)throw new Error('Invalid placement heights.');for(const p of layer.placementHeights){if(!Array.isArray(p)||p.length<2||!Number.isInteger(+p[0])||+p[0]<0||+p[0]>=w*h||!Number.isFinite(+p[1])||+p[1]<0||+p[1]>512)throw new Error('Invalid placement height.');}}}
    }

    setPerformanceStats(enabled:boolean){this.performanceStatsBox.classList.toggle('hidden',!enabled);this.renderer.setPerformanceStats(enabled,s=>this.updatePerformanceStats(s));if(enabled)this.updatePerformanceStats(this.renderer.performanceStats());}
    updatePerformanceStats(s:PerformanceStats){this.performanceStatsBox.textContent=`FPS              ${s.fps.toFixed(1)}\nFrame time       ${s.frameMs.toFixed(2)} ms\nVisible chunks   ${s.visibleChunks} / ${s.totalChunks}\nVisible sprites  ${s.visibleSprites.toLocaleString()}\nDraw calls       ${s.drawCalls.toLocaleString()}\nGPU textures     ${s.activeTextures.toLocaleString()}\nCached batches   ${s.cachedChunkBatches.toLocaleString()}\nDirty chunks     ${s.dirtyChunks}`;}


  }
  addEventListener('DOMContentLoaded',()=>{try{(window as any).pzOnlineDecorationTool=new App();}catch(e){console.error(e);const s=document.getElementById('status');if(s)s.textContent=`Startup error: ${String((e as Error).message||e)}`;}});
}
