/*
 * PZ Online Decoration Tool
 * Copyright (C) 2026 PZ Online Decoration Tool contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
namespace PZODT {
  interface SheetRecord{name:string;file:File;path:string;scale:number;width:number;height:number;indexed:boolean;sourceId?:string;}
  export class AssetManager{
    assets=new Map<string,AssetRef>();sources=new Map<string,ImageSourceRecord>();sheets=new Map<string,SheetRecord>();private byKey=new Map<string,AssetRef>();private imageBitmaps=new Map<string,Promise<ImageBitmap>>();private legacyTreePools:Map<number,AssetRef[]>|null=null;private sourceSeq=1;loadedFileKeys=new Set<string>();onChanged:()=>void=()=>{};
    fileKey(f:File):string{const p=((f as any).webkitRelativePath||f.name).replace(/\\/g,'/');return `${p}|${f.size}|${f.lastModified}`;}
    addImageSource(label:string,blob:Blob,w:number,h:number):string{const id=`src-${this.sourceSeq++}`,objectUrl=URL.createObjectURL(blob);this.sources.set(id,{id,label,width:w,height:h,blob,objectUrl});return id;}
    private tileKey(name:string):string{const p=parseTileName(name);return `${p.tilesetName.toLowerCase()}:${p.tileIndex}`;}
    addAsset(a:AssetRef):void{const old=this.assets.get(a.name);if(!old||a.scale>=old.scale)this.assets.set(a.name,a);const k=`${a.tilesetName.toLowerCase()}:${a.tileIndex}`,ok=this.byKey.get(k);if(!ok||a.scale>=ok.scale)this.byKey.set(k,a);this.legacyTreePools=null;}
    asset(name:string):AssetRef|null{return this.assets.get(name)??this.byKey.get(this.tileKey(name))??null;}
    async bitmap(sourceId:string):Promise<ImageBitmap>{let p=this.imageBitmaps.get(sourceId);if(p)return p;const s=this.sources.get(sourceId);if(!s)throw new Error('Missing source');p=createImageBitmap(s.blob).then(b=>{if(!s.width){s.width=b.width;s.height=b.height;}return b;});this.imageBitmaps.set(sourceId,p);return p;}
    clear():void{for(const s of this.sources.values())URL.revokeObjectURL(s.objectUrl);this.assets.clear();this.sources.clear();this.sheets.clear();this.byKey.clear();this.imageBitmaps.clear();this.legacyTreePools=null;this.loadedFileKeys.clear();this.onChanged();}
    dominantScale():number{let a=0,b=0,i=0;for(const x of this.assets.values()){x.scale>=2?b++:a++;if(++i>5000)break;}return b>a?2:1;}
    private frame(name:string,scale:number):{w:number;h:number}{let w=64,h=128,n=name.toUpperCase();if(n.includes('JUMBOXXL_')){w=448;h=512;}else if(n.includes('JUMBOXL_')){w=320;h=384;}else if(n.includes('JUMBO_')){w=192;h=256;}return{w:w*scale,h:h*scale};}
    private indexSheet(sh:SheetRecord):void{if(sh.indexed||!sh.width||!sh.height)return;const fr=this.frame(sh.name,sh.scale),cols=Math.floor(sh.width/fr.w),rows=Math.floor(sh.height/fr.h);if(cols<1||rows<1)return;const sid=this.addImageSource(sh.path,sh.file,sh.width,sh.height);sh.sourceId=sid;let id=0;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++,id++)this.addAsset({name:`${sh.name}_${String(id).padStart(3,'0')}`,sourceId:sid,tilesetName:sh.name,tileIndex:id,sx:x*fr.w,sy:y*fr.h,sw:fr.w,sh:fr.h,frameW:fr.w,frameH:fr.h,offsetX:0,offsetY:0,scale:sh.scale});sh.indexed=true;}
    async loadMediaFiles(files:File[],progress?:(s:string)=>void):Promise<{png:number;packs:number;skipped:number}>{const fresh=files.filter(f=>!this.loadedFileKeys.has(this.fileKey(f)));const pngs=fresh.filter(f=>/\.png$/i.test(f.name)),packs=fresh.filter(f=>/\.pack$/i.test(f.name));let skipped=files.length-fresh.length;const best=new Map<string,{f:File,path:string,scale:number}>();for(const f of pngs){const path=((f as any).webkitRelativePath||f.name).replace(/\\/g,'/'),scale=/(^|\/)2x(\/|$)/i.test(path)?2:1,key=f.name.toLowerCase(),old=best.get(key);if(!old||scale>old.scale)best.set(key,{f,path,scale});}
      for(const {f,path,scale} of best.values()){const name=f.name.replace(/\.png$/i,'');this.sheets.set(name,{name,file:f,path,scale,width:0,height:0,indexed:false});}
      const q=[...this.sheets.values()].filter(x=>!x.indexed);let done=0;const total=q.length;const workers=Array.from({length:Math.min(6,q.length)},async()=>{while(q.length){const sh=q.shift()!;try{const bm=await createImageBitmap(sh.file);sh.width=bm.width;sh.height=bm.height;bm.close();this.indexSheet(sh);}catch(e){console.warn(e);}done++;if(done%10===0||done===total)progress?.(`PNG tilesheets ${done}/${total} · ${this.assets.size.toLocaleString()} sprites`);}});await Promise.all(workers);
      for(let i=0;i<packs.length;i++){progress?.(`Reading texture pack ${i+1}/${packs.length}: ${packs[i].name}`);try{await parsePZPack(packs[i],this,progress);}catch(e){console.warn('Pack failed',packs[i].name,e);}}
      for(const f of fresh)this.loadedFileKeys.add(this.fileKey(f));this.onChanged();return{png:pngs.length,packs:packs.length,skipped};}
    private buildLegacyTreePools():Map<number,AssetRef[]>{if(this.legacyTreePools)return this.legacyTreePools;const pools=new Map<number,AssetRef[]>(),groups=new Map<string,AssetRef[]>(),push=(size:number,a:AssetRef)=>{const p=pools.get(size)??[];p.push(a);pools.set(size,p);};for(const a of this.assets.values()){if(!/^e_/i.test(a.tilesetName))continue;const g=groups.get(a.tilesetName)??[];g.push(a);groups.set(a.tilesetName,g);}for(const [name,items] of groups){const n=name.toUpperCase(),max=Math.max(...items.map(a=>a.tileIndex));if(n.includes('JUMBOXXL_')){const target=max>=5?3:0;for(const a of items)if(a.tileIndex===target)push(8,a);continue;}if(n.includes('JUMBOXL_')){const target=max>=5?3:0;for(const a of items)if(a.tileIndex===target)push(7,a);continue;}if(n.includes('JUMBO_')){const green=max>=11?[6,7]:[0,1];for(const a of items){const j=green.indexOf(a.tileIndex);if(j>=0)push(5+j,a);}continue;}if(/_1$/i.test(name)){const green=max>=23?[12,13,14,15]:[0,1,2,3];for(const a of items){const j=green.indexOf(a.tileIndex);if(j>=0)push(1+j,a);}}}this.legacyTreePools=pools;return pools;}
    legacyTreeAsset(name:string,worldX:number,worldY:number):AssetRef|null{const p=parseTileName(name);if(p.tilesetName.toLowerCase()!=='vegetation_trees_01')return null;const pools=this.buildLegacyTreePools();if(!pools.size)return null;let h=(Math.imul(worldX|0,73856093)^Math.imul(worldY|0,19349663)^Math.imul((p.tileIndex|0)+1,83492791))>>>0;h^=h>>>13;h=Math.imul(h,1274126177)>>>0;const r=h%1000;let size=r<25?8:r<60?7:r<140?6:r<260?5:1+((h>>>10)&3),pool=pools.get(size);if(!pool?.length){for(const s of [4,3,2,1,5,6,7,8])if(pools.get(s)?.length){pool=pools.get(s);break;}}if(!pool?.length)return null;return pool[(h>>>16)%pool.length]??pool[0]??null;}
    tilesetNames():string[]{const s=new Set<string>();for(const a of this.assets.values())s.add(a.tilesetName);return [...s].sort();}
    search(q:string,limit=600,extra?:(a:AssetRef)=>string):AssetRef[]{const out:AssetRef[]=[];for(const a of this.assets.values()){if(!q||searchMatches(`${a.name} ${a.tilesetName} ${extra?.(a)??''}`,q))out.push(a);}return out.sort((a,b)=>a.name.localeCompare(b.name)).slice(0,limit);}
    assetsForTileset(n:string):AssetRef[]{return [...this.assets.values()].filter(a=>a.tilesetName===n).sort((a,b)=>a.tileIndex-b.tileIndex);}
    async drawPreview(c:HTMLCanvasElement,name:string):Promise<void>{const a=this.asset(name),ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);if(!a)return;const b=await this.bitmap(a.sourceId),fit=Math.min(c.width/a.frameW,c.height/a.frameH,1),x=(c.width-a.frameW*fit)/2+a.offsetX*fit,y=(c.height-a.frameH*fit)/2+a.offsetY*fit;ctx.imageSmoothingEnabled=false;ctx.drawImage(b,a.sx,a.sy,a.sw,a.sh,x,y,a.sw*fit,a.sh*fit);}
  }
}
