/*
 * PZ Online Decoration Tool
 * Copyright (C) 2026 PZ Online Decoration Tool contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
namespace PZODT {
  interface SheetRecord{name:string;file:File;path:string;scale:number;width:number;height:number;indexed:boolean;sourceId?:string;}
  export class AssetManager{
    assets=new Map<string,AssetRef>();sources=new Map<string,ImageSourceRecord>();sheets=new Map<string,SheetRecord>();private byKey=new Map<string,AssetRef>();private tilesetStats=new Map<string,{count:number;maxScale:number}>();private imageBitmaps=new Map<string,Promise<ImageBitmap>>();private legacyTreeFamilies:AssetRef[][]|null=null;private sourceSeq=1;loadedFileKeys=new Set<string>();onChanged:()=>void=()=>{};
    fileKey(f:File):string{const p=((f as any).webkitRelativePath||f.name).replace(/\\/g,'/');return `${p}|${f.size}|${f.lastModified}`;}
    addImageSource(label:string,blob:Blob,w:number,h:number):string{const id=`src-${this.sourceSeq++}`,objectUrl=URL.createObjectURL(blob);this.sources.set(id,{id,label,width:w,height:h,blob,objectUrl});return id;}
    private tileKey(name:string):string{const p=parseTileName(name);return `${p.tilesetName.toLowerCase()}:${p.tileIndex}`;}
    addAsset(a:AssetRef):void{const old=this.assets.get(a.name);if(!old||a.scale>=old.scale)this.assets.set(a.name,a);const k=`${a.tilesetName.toLowerCase()}:${a.tileIndex}`,ok=this.byKey.get(k),ts=a.tilesetName.toLowerCase();if(!ok){const stat=this.tilesetStats.get(ts)??{count:0,maxScale:0};stat.count++;stat.maxScale=Math.max(stat.maxScale,a.scale);this.tilesetStats.set(ts,stat);}else{const stat=this.tilesetStats.get(ts)??{count:1,maxScale:ok.scale};stat.maxScale=Math.max(stat.maxScale,a.scale);this.tilesetStats.set(ts,stat);}if(!ok||a.scale>=ok.scale)this.byKey.set(k,a);this.legacyTreeFamilies=null;}
    private tilesetCoverage(name:string){return this.tilesetStats.get(name.toLowerCase())??{count:0,maxScale:0};}
    asset(name:string):AssetRef|null{return this.assets.get(name)??this.byKey.get(this.tileKey(name))??null;}
    isLegacyTreePlaceholder(name:string):boolean{return /^vegetation_trees_01_\d+$/i.test(name);}
    resolveAsset(name:string,worldX=0,worldY=0):AssetRef|null{return this.isLegacyTreePlaceholder(name)?this.legacyTreeAsset(name,worldX,worldY):this.asset(name);}
    async bitmap(sourceId:string):Promise<ImageBitmap>{let p=this.imageBitmaps.get(sourceId);if(p)return p;const s=this.sources.get(sourceId);if(!s)throw new Error('Missing source');p=createImageBitmap(s.blob).then(b=>{if(!s.width){s.width=b.width;s.height=b.height;}return b;});this.imageBitmaps.set(sourceId,p);return p;}
    clear():void{for(const s of this.sources.values())URL.revokeObjectURL(s.objectUrl);this.assets.clear();this.sources.clear();this.sheets.clear();this.byKey.clear();this.tilesetStats.clear();this.imageBitmaps.clear();this.legacyTreeFamilies=null;this.loadedFileKeys.clear();this.onChanged();}
    dominantScale():number{let a=0,b=0,i=0;for(const x of this.assets.values()){x.scale>=2?b++:a++;if(++i>5000)break;}return b>a?2:1;}
    private frame(name:string,scale:number):{w:number;h:number}{let w=64,h=128,n=name.toUpperCase();if(n.includes('JUMBOXXL_')){w=448;h=512;}else if(n.includes('JUMBOXL_')){w=320;h=384;}else if(n.includes('JUMBO_')){w=192;h=256;}return{w:w*scale,h:h*scale};}
    private indexSheet(sh:SheetRecord):void{if(sh.indexed||!sh.width||!sh.height)return;const fr=this.frame(sh.name,sh.scale),cols=Math.floor(sh.width/fr.w),rows=Math.floor(sh.height/fr.h);if(cols<1||rows<1)return;const sid=this.addImageSource(sh.path,sh.file,sh.width,sh.height);sh.sourceId=sid;let id=0;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++,id++)this.addAsset({name:`${sh.name}_${String(id).padStart(3,'0')}`,sourceId:sid,tilesetName:sh.name,tileIndex:id,sx:x*fr.w,sy:y*fr.h,sw:fr.w,sh:fr.h,frameW:fr.w,frameH:fr.h,offsetX:0,offsetY:0,scale:sh.scale});sh.indexed=true;}
    async loadMediaFiles(files:File[],progress?:(s:string)=>void,expectedCounts?:Promise<(tileset:string)=>number>):Promise<{png:number;packs:number;skipped:number;pngSkipped:number}>{const fresh=files.filter(f=>!this.loadedFileKeys.has(this.fileKey(f))),pngs=fresh.filter(f=>/\.png$/i.test(f.name)),packs=fresh.filter(f=>/\.pack$/i.test(f.name));let skipped=files.length-fresh.length,pngSkipped=0;const best=new Map<string,{f:File,path:string;scale:number}>();for(const f of pngs){const path=((f as any).webkitRelativePath||f.name).replace(/\\/g,'/'),scale=/(^|\/)2x(\/|$)/i.test(path)?2:1,key=f.name.toLowerCase(),old=best.get(key);if(!old||scale>old.scale)best.set(key,{f,path,scale});}for(const {f,path,scale} of best.values()){const name=f.name.replace(/\.png$/i,'');this.sheets.set(name,{name,file:f,path,scale,width:0,height:0,indexed:false});}
      const packQueue=[...packs];let packDone=0;const packWorkers=Array.from({length:Math.min(2,packQueue.length)},async()=>{while(packQueue.length){const f=packQueue.shift()!;try{await parsePZPack(f,this);}catch(e){console.warn('Pack failed',f.name,e);}packDone++;if(packDone===packs.length||packDone%2===0)progress?.(`Texture packs ${packDone}/${packs.length} · ${this.assets.size.toLocaleString()} sprites`);}});await Promise.all(packWorkers);
      const expected=expectedCounts?await expectedCounts:undefined,q=[...this.sheets.values()].filter(x=>!x.indexed).filter(sh=>{const c=this.tilesetCoverage(sh.name),need=expected?.(sh.name)??0,covered=c.maxScale>=sh.scale&&need>0&&c.count>=need;if(covered){sh.indexed=true;pngSkipped++;return false;}return true;});let done=0;const total=q.length,workers=Array.from({length:Math.min(8,q.length)},async()=>{while(q.length){const sh=q.shift()!;try{const bm=await createImageBitmap(sh.file);sh.width=bm.width;sh.height=bm.height;bm.close();this.indexSheet(sh);}catch(e){console.warn(e);}done++;if(done===total||done%12===0)progress?.(`PNG fallbacks ${done}/${total} · ${pngSkipped.toLocaleString()} duplicate sheet(s) skipped · ${this.assets.size.toLocaleString()} sprites`);}});await Promise.all(workers);
      for(const f of fresh)this.loadedFileKeys.add(this.fileKey(f));this.onChanged();return{png:pngs.length,packs:packs.length,skipped,pngSkipped};}
    private buildLegacyTreeFamilies():AssetRef[][]{if(this.legacyTreeFamilies)return this.legacyTreeFamilies;const names=['e_americanholly_1','e_canadianhemlock_1','e_virginiapine_1','e_riverbirch_1','e_cockspurhawthorn_1','e_dogwood_1','e_carolinasilverbell_1','e_yellowwood_1','e_easternredbud_1','e_redmaple_1','e_americanlinden_1'];this.legacyTreeFamilies=names.map(n=>[0,1,2,3].map(stage=>this.asset(`${n}_${stage}`)).filter((a):a is AssetRef=>!!a));return this.legacyTreeFamilies;}
    legacyTreeAsset(name:string,worldX:number,worldY:number):AssetRef|null{const p=parseTileName(name);if(p.tilesetName.toLowerCase()!=='vegetation_trees_01')return null;const families=this.buildLegacyTreeFamilies();if(!families.some(x=>x.length))return null;const soilRef=[[2,4,4,4,5,5,5,5,5,5,5],[1,1,2,2,2,4,4,4,4,4,4,4,4,4,4,5,5,5,5],[2,2,2,2,2,2,2,2,1,1,1,1,3,3,4,4,4,5],[1,7,7,7,9,9,9,9,9,9,9],[2,2,1,1,1,7,7,7,7,7,7,7,7,7,7,9,9,9,9],[1,1,1,1,1,1,1,1,2,2,2,2,3,3,7,7,7,9],[1,2,8,8,8,6,6,6,6,6,6,6,6],[1,1,2,2,3,8,8,8,8,8,8,8,8,8,8,6,6,6,6,6],[1,1,1,1,1,1,2,2,2,2,2,2,3,3,8,8,8,6],[3,10,10,10,11,11,11,11,11,11,11],[1,1,3,3,3,10,10,10,10,10,10,10,10,10,10,11,11,11,11],[1,1,1,1,2,2,2,2,3,3,3,3,3,3,3,3,10,10,10,11]];let h=(Math.imul(worldX|0,73856093)^Math.imul(worldY|0,19349663)^Math.imul((p.tileIndex|0)+1,83492791))>>>0;h^=h>>>13;h=Math.imul(h,1274126177)>>>0;const soil=h%soilRef.length,choices=soilRef[soil],familyIndex=choices[(h>>>8)%choices.length]-1,stage=2+(((h>>>16)%101)>=51?1:0);const family=families[familyIndex]??[];const exact=family.find(a=>a.tileIndex===stage);if(exact)return exact;for(const fallbackStage of [3,2,1,0]){const a=family.find(x=>x.tileIndex===fallbackStage);if(a)return a;}for(const alt of families){const a=alt.find(x=>x.tileIndex===stage)??alt.find(x=>x.tileIndex===3)??alt.find(x=>x.tileIndex===2);if(a)return a;}return null;}
    tilesetNames():string[]{const s=new Set<string>();for(const a of this.assets.values())s.add(a.tilesetName);return [...s].sort();}
    search(q:string,limit=600,extra?:(a:AssetRef)=>string):AssetRef[]{const out:AssetRef[]=[];for(const a of this.assets.values()){if(!q||searchMatches(`${a.name} ${a.tilesetName} ${extra?.(a)??''}`,q))out.push(a);}return out.sort((a,b)=>a.name.localeCompare(b.name)).slice(0,limit);}
    assetsForTileset(n:string):AssetRef[]{return [...this.assets.values()].filter(a=>a.tilesetName===n).sort((a,b)=>a.tileIndex-b.tileIndex);}
    async drawPreview(c:HTMLCanvasElement,name:string,worldX=0,worldY=0):Promise<void>{const a=this.resolveAsset(name,worldX,worldY),ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);if(!a)return;const b=await this.bitmap(a.sourceId),fit=Math.min(c.width/a.frameW,c.height/a.frameH,1),x=(c.width-a.frameW*fit)/2+a.offsetX*fit,y=(c.height-a.frameH*fit)/2+a.offsetY*fit;ctx.imageSmoothingEnabled=false;ctx.drawImage(b,a.sx,a.sy,a.sw,a.sh,x,y,a.sw*fit,a.sh*fit);}
  }
}
