namespace PZODT {
  export type PZImportMode='building'|'area'|'cell';
  export interface PZImportOptions{datasetId:string;x:number;y:number;mode:PZImportMode;margin:number;areaWidth:number;areaHeight:number;}
  export interface PZImportResult{map:PZMapModel;usedTiles:Set<string>;importedSquares:number;importedSprites:number;bounds:{x:number;y:number;w:number;h:number};buildingName?:string;}
  interface LotRect{x:number;y:number;w:number;h:number;} interface LotRoom{id:number;name:string;level:number;rects:LotRect[];buildingIndex:number;} interface LotBuilding{id:number;roomIds:number[];}
  interface Header{cellX:number;cellY:number;version:number;tiles:string[];chunkW:number;chunkH:number;minLevel:number;maxLevel:number;rooms:LotRoom[];buildings:LotBuilding[];}
  interface PackInfo{version:number;chunkCount:number;chunksPerCell:number;offsets:number[];data:ArrayBuffer;}
  interface Dataset{id:string;path:string;headers:Map<string,File>;packs:Map<string,File>;cellSize?:number;chunksPerCell?:number;chunkW?:number;chunkH?:number;}
  interface Bounds{x0:number;y0:number;x1:number;y1:number;}
  class R{v:DataView;b:Uint8Array;p=0;constructor(x:ArrayBuffer){this.v=new DataView(x);this.b=new Uint8Array(x);}i32(){if(this.p+4>this.b.length)throw new Error('Truncated map file');const x=this.v.getInt32(this.p,true);this.p+=4;return x;}i64(){if(this.p+8>this.b.length)throw new Error('Truncated map file');const x=Number(this.v.getBigInt64(this.p,true));this.p+=8;return x;}u8(){if(this.p>=this.b.length)throw new Error('Truncated map file');return this.b[this.p++];}ascii(n:number){let s='';while(n--)s+=String.fromCharCode(this.u8());return s;}line(){let s='';while(this.p<this.b.length){const c=this.u8();if(c===10)break;s+=String.fromCharCode(c);}return s.trim();}seek(n:number){this.p=n;}}
  const key=(x:number,y:number)=>`${x},${y}`,path=(f:File)=>((f as any).webkitRelativePath||f.name).replace(/\\/g,'/'),dir=(p:string)=>p.includes('/')?p.slice(0,p.lastIndexOf('/')):'',base=(p:string)=>p.slice(p.lastIndexOf('/')+1),W=(b:Bounds)=>b.x1-b.x0+1,H=(b:Bounds)=>b.y1-b.y0+1;
  const union=(a:Bounds|null,b:Bounds):Bounds=>a?{x0:Math.min(a.x0,b.x0),y0:Math.min(a.y0,b.y0),x1:Math.max(a.x1,b.x1),y1:Math.max(a.y1,b.y1)}:b;
  export class PZWorldImportManager{
    datasets=new Map<string,Dataset>();allFiles:File[]=[];mediaSignature='';private hcache=new Map<string,Promise<Header>>();private pcache=new Map<string,Promise<PackInfo>>();
    scan(files:FileList|File[]):Array<{id:string;label:string;headers:number;packs:number}>{const arr=Array.from(files);this.allFiles=arr;this.datasets.clear();this.hcache.clear();this.pcache.clear();let sigParts:string[]=[];for(const f of arr){const p=path(f),bn=base(p);sigParts.push(`${p}:${f.size}:${f.lastModified}`);let m=bn.match(/^(-?\d+)_(-?\d+)\.lotheader$/i);if(m){const d=dir(p),ds=this.datasets.get(d)??{id:d,path:d,headers:new Map(),packs:new Map()};ds.headers.set(key(+m[1],+m[2]),f);this.datasets.set(d,ds);continue;}m=bn.match(/^world_(-?\d+)_(-?\d+)\.lotpack$/i);if(m){const d=dir(p),ds=this.datasets.get(d)??{id:d,path:d,headers:new Map(),packs:new Map()};ds.packs.set(key(+m[1],+m[2]),f);this.datasets.set(d,ds);}}sigParts.sort();let hash=2166136261;for(const s of sigParts)for(let i=0;i<s.length;i++){hash^=s.charCodeAt(i);hash=Math.imul(hash,16777619);}this.mediaSignature=`${arr.length}:${hash>>>0}`;return [...this.datasets.values()].filter(d=>d.headers.size).sort((a,b)=>b.headers.size-a.headers.size).map(d=>({id:d.id,label:d.path||'(media)',headers:d.headers.size,packs:d.packs.size}));}
    assetFiles():File[]{return this.allFiles.filter(f=>/\.(png|pack)$/i.test(f.name));} tileDefFiles():File[]{return this.allFiles.filter(f=>/\.tiles$/i.test(f.name));}
    private async header(ds:Dataset,f:File,cx:number,cy:number):Promise<Header>{const ck=`${ds.id}|H|${cx},${cy}`;let q=this.hcache.get(ck);if(q)return q;q=(async()=>{const r=new R(await f.arrayBuffer());let version=0,magic=r.ascii(4);if(magic==='LOTH'){version=r.i32();}else{r.seek(0);version=r.i32();}if(version<0||version>1)throw new Error(`Unsupported lotheader version ${version}`);const nt=r.i32(),tiles:string[]=[];if(nt<0||nt>300000)throw new Error('Invalid tile list');for(let i=0;i<nt;i++)tiles.push(r.line());if(version===0)r.u8();const chunkW=r.i32(),chunkH=r.i32();let min=0,max=0;if(version===0){min=0;max=r.i32()-1;}else{min=r.i32();max=r.i32();}const nr=r.i32(),rooms:LotRoom[]=[];for(let i=0;i<nr;i++){const name=r.line(),level=r.i32(),rc=r.i32(),rects:LotRect[]=[];for(let j=0;j<rc;j++)rects.push({x:r.i32(),y:r.i32(),w:r.i32(),h:r.i32()});const no=r.i32();for(let j=0;j<no;j++){r.i32();r.i32();r.i32();}rooms.push({id:i,name,level,rects,buildingIndex:-1});}const nb=r.i32(),buildings:LotBuilding[]=[];for(let i=0;i<nb;i++){const n=r.i32(),ids:number[]=[];for(let j=0;j<n;j++){const id=r.i32();ids.push(id);if(rooms[id])rooms[id].buildingIndex=i;}buildings.push({id:i,roomIds:ids});}return{cellX:cx,cellY:cy,version,tiles,chunkW,chunkH,minLevel:min,maxLevel:max,rooms,buildings};})();this.hcache.set(ck,q);return q;}
    private async pack(ds:Dataset,f:File,k:string):Promise<PackInfo>{const ck=`${ds.id}|P|${k}`;let q=this.pcache.get(ck);if(q)return q;q=(async()=>{const data=await f.arrayBuffer(),r=new R(data);let version=0,n=0,magic=r.ascii(4);if(magic==='LOTP'){version=r.i32();n=r.i32();}else{r.seek(0);n=r.i32();}if(n<=0||n>100000)throw new Error('Invalid lotpack table');const c=Math.round(Math.sqrt(n));if(c*c!==n)throw new Error('Invalid chunk grid');const offsets:number[]=[];for(let i=0;i<n;i++)offsets.push(r.i64());return{version,chunkCount:n,chunksPerCell:c,offsets,data};})();this.pcache.set(ck,q);return q;}
    private async geom(ds:Dataset):Promise<void>{if(ds.cellSize)return;const e=[...ds.headers.entries()].find(([k])=>ds.packs.has(k))??[...ds.headers.entries()][0];if(!e)throw new Error('No map headers');const [k0,hf]=e,[cx,cy]=k0.split(',').map(Number),h=await this.header(ds,hf,cx,cy),pf=ds.packs.get(k0);let c=32;if(pf)c=(await this.pack(ds,pf,k0)).chunksPerCell;else if(h.version===0)c=30;ds.chunksPerCell=c;ds.chunkW=h.chunkW;ds.chunkH=h.chunkH;ds.cellSize=c*h.chunkW;}
    private roomBounds(ds:Dataset,h:Header,r:LotRoom):Bounds|null{if(!ds.cellSize)return null;let b:Bounds|null=null;for(const q of r.rects){const x=h.cellX*ds.cellSize+q.x,y=h.cellY*ds.cellSize+q.y;b=union(b,{x0:x,y0:y,x1:x+q.w-1,y1:y+q.h-1});}return b;}
    private buildingBounds(ds:Dataset,h:Header,bld:LotBuilding):Bounds|null{let b:Bounds|null=null;for(const id of bld.roomIds){const r=h.rooms[id],rb=r?this.roomBounds(ds,h,r):null;if(rb)b=union(b,rb);}return b;}
    private async findBuilding(ds:Dataset,x:number,y:number):Promise<{b:Bounds;min:number;max:number;name:string}|null>{await this.geom(ds);const cs=ds.cellSize!,cx=Math.floor(x/cs),cy=Math.floor(y/cs),hits:Array<any>=[];for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const k=key(cx+dx,cy+dy),f=ds.headers.get(k);if(!f)continue;const h=await this.header(ds,f,cx+dx,cy+dy);for(const bld of h.buildings){const b=this.buildingBounds(ds,h,bld);if(!b)continue;let min=99,max=-99,inside=false,names=new Set<string>();for(const id of bld.roomIds){const r=h.rooms[id];if(!r)continue;min=Math.min(min,r.level);max=Math.max(max,r.level);names.add(r.name);const rb=this.roomBounds(ds,h,r);if(rb&&x>=rb.x0&&x<=rb.x1&&y>=rb.y0&&y<=rb.y1)inside=true;}const dd=Math.hypot(x< b.x0?b.x0-x:x>b.x1?x-b.x1:0,y<b.y0?b.y0-y:y>b.y1?y-b.y1:0);if(inside||dd<=3)hits.push({b,min:min===99?0:min,max:max<0?0:max,name:[...names].slice(0,3).join(', ')||'Building',score:(inside?0:1)*1e9+dd*1e6+W(b)*H(b)});}}hits.sort((a,b)=>a.score-b.score);return hits[0]??null;}
    private async range(ds:Dataset,b:Bounds):Promise<{min:number;max:number}>{await this.geom(ds);const cs=ds.cellSize!;let min=99,max=-99;for(let cx=Math.floor(b.x0/cs);cx<=Math.floor(b.x1/cs);cx++)for(let cy=Math.floor(b.y0/cs);cy<=Math.floor(b.y1/cs);cy++){const f=ds.headers.get(key(cx,cy));if(!f)continue;const h=await this.header(ds,f,cx,cy);min=Math.min(min,h.minLevel);max=Math.max(max,h.maxLevel);}return{min:min===99?0:min,max:max<0?0:max};}
    async importLocation(o:PZImportOptions,progress?:(s:string)=>void):Promise<PZImportResult>{const ds=this.datasets.get(o.datasetId);if(!ds)throw new Error('Select a map dataset');await this.geom(ds);const cs=ds.cellSize!;let b:Bounds,min=0,max=0,name:string|undefined;if(o.mode==='building'){progress?.('Finding building…');const hit=await this.findBuilding(ds,o.x,o.y);if(!hit)throw new Error('No building found at this coordinate. Try Area mode.');b={x0:hit.b.x0-o.margin,y0:hit.b.y0-o.margin,x1:hit.b.x1+o.margin,y1:hit.b.y1+o.margin};min=hit.min;max=hit.max+1;name=hit.name;}else if(o.mode==='cell'){const cx=Math.floor(o.x/cs),cy=Math.floor(o.y/cs);b={x0:cx*cs,y0:cy*cs,x1:(cx+1)*cs-1,y1:(cy+1)*cs-1};({min,max}=await this.range(ds,b));}else{const w=Math.max(1,Math.min(300,o.areaWidth|0)),h=Math.max(1,Math.min(300,o.areaHeight|0));b={x0:o.x-Math.floor(w/2),y0:o.y-Math.floor(h/2),x1:o.x-Math.floor(w/2)+w-1,y1:o.y-Math.floor(h/2)+h-1};({min,max}=await this.range(ds,b));}
      const w=W(b),h=H(b);if(w>600||h>600)throw new Error(`Import area too large: ${w}×${h}`);const map=new PZMapModel(w,h);map.currentLevel=Math.max(min,Math.min(max,0));map.properties={'pzodt.worldOriginX':String(b.x0),'pzodt.worldOriginY':String(b.y0),'pzodt.dataset':ds.path};const used=new Set<string>();let squares=0,sprites=0;
      for(let z=min;z<=max;z++){progress?.(`Reading Z ${z}…`);const cx0=Math.floor(b.x0/cs),cy0=Math.floor(b.y0/cs),cx1=Math.floor(b.x1/cs),cy1=Math.floor(b.y1/cs);for(let cx=cx0;cx<=cx1;cx++)for(let cy=cy0;cy<=cy1;cy++){const k=key(cx,cy),hf=ds.headers.get(k),pf=ds.packs.get(k);if(!hf||!pf)continue;const hd=await this.header(ds,hf,cx,cy);if(z<hd.minLevel||z>hd.maxLevel)continue;const pi=await this.pack(ds,pf,k),local={x0:Math.max(0,b.x0-cx*cs),y0:Math.max(0,b.y0-cy*cs),x1:Math.min(cs-1,b.x1-cx*cs),y1:Math.min(cs-1,b.y1-cy*cs)};this.readRect(hd,pi,z,local,(lx,ly,names)=>{const wx=cx*cs+lx,wy=cy*cs+ly,x=wx-b.x0,y=wy-b.y0;if(x<0||y<0||x>=w||y>=h)return;map.setStack(z,x,y,names);squares++;sprites+=names.length;for(const n of names)used.add(n);});}}
      return{map,usedTiles:used,importedSquares:squares,importedSprites:sprites,bounds:{x:b.x0,y:b.y0,w,h},buildingName:name};}
    private readRect(h:Header,p:PackInfo,zWanted:number,b:Bounds,emit:(x:number,y:number,n:string[])=>void):void{const cw=h.chunkW,ch=h.chunkH,cpc=p.chunksPerCell;for(let cx=Math.floor(b.x0/cw);cx<=Math.floor(b.x1/cw);cx++)for(let cy=Math.floor(b.y0/ch);cy<=Math.floor(b.y1/ch);cy++){const idx=cx*cpc+cy,off=p.offsets[idx];if(!Number.isFinite(off)||off<0||off>=p.data.byteLength)continue;const r=new R(p.data);r.seek(off);let skip=0;for(let z=h.minLevel;z<=h.maxLevel;z++)for(let x=0;x<cw;x++)for(let y=0;y<ch;y++){if(skip>0){skip--;continue;}const count=r.i32();if(count===-1){skip=r.i32();if(skip>0)skip--;continue;}if(count<1||count>100)throw new Error('Invalid lotpack square');r.i32();const names:string[]=[];for(let n=1;n<count;n++){const id=r.i32();if(id>=0&&id<h.tiles.length)names.push(h.tiles[id]);}if(z!==zWanted||!names.length)continue;const lx=cx*cw+x,ly=cy*ch+y;if(lx>=b.x0&&lx<=b.x1&&ly>=b.y0&&ly<=b.y1)emit(lx,ly,names);}}}
  }
}
